### ISSUE TITLE
Not able to connect to localhost using root account and no password

### ISSUE THREAD

**Issue by VasuInukollu** [skeema/skeema#108]
root@rws:~# mysql -h localhost -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3375
Server version: 10.1.41-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye

root@rws:~# skeema init -d Database -h localhost -u root
2019-11-11 17:32:07 [ERROR] Unable to connect to localhost:/tmp/mysql.sock for /root/Database: dial unix /tmp/mysql.sock: connect: no such file or directory

**Comment by VasuInukollu** [comment]
When used against MariaDb, the socket name discovery is not happening. The following is working just fine.

**skeema init -h localhost --socket "/var/run/mysqld/mysqld.sock"**

**Comment by VasuInukollu** [comment]
Results are not consistent when using socket.

root@rws:~/database/localhost# skeema diff --allow-unsafe
[mysql] 2019/11/11 18:23:05 packets.go:36: read unix @->/var/run/mysqld/mysqld.sock: i/o timeout
[mysql] 2019/11/11 18:23:05 packets.go:36: read unix @->/var/run/mysqld/mysqld.sock: i/o timeout
[mysql] 2019/11/11 18:23:05 packets.go:36: read unix @->/var/run/mysqld/mysqld.sock: i/o timeout
[mysql] 2019/11/11 18:23:05 packets.go:36: read unix @->/var/run/mysqld/mysqld.sock: i/o timeout
[mysql] 2019/11/11 18:23:05 packets.go:36: read unix @->/var/run/mysqld/mysqld.sock: i/o timeout
[mysql] 2019/11/11 18:23:05 packets.go:36: read unix @->/var/run/mysqld/mysqld.sock: i/o timeout
2019-11-11 18:23:10 [ERROR] /root/database/localhost/Xema/Agents.sql:1:1: Error executing DDL in workspace: invalid connection
2019-11-11 18:23:10 [ERROR] /root/database/localhost/Xema/CrmUrls.sql:1:1: Error executing DDL in workspace: invalid connection
2019-11-11 18:23:10 [ERROR] /root/database/localhost/Xema/Queues.sql:1:1: Error executing DDL in workspace: invalid connection
2019-11-11 18:23:10 [ERROR] /root/database/localhost/Xema/Teams.sql:1:1: Error executing DDL in workspace: invalid connection
2019-11-11 18:23:10 [ERROR] /root/database/localhost/Xema/AudioFiles.sql:1:1: Error executing DDL in workspace: invalid connection
2019-11-11 18:23:10 [ERROR] /root/database/localhost/Xema/AgentSkills.sql:1:1: Error executing DDL in workspace: invalid connection
2019-11-11 18:23:10 [WARN]  Skipping /root/database/localhost/Xema due to 6 SQL errors

2019-11-11 18:23:10 [INFO]  Generating diff of localhost:/var/run/mysqld/mysqld.sock Auth vs /root/database/localhost/Auth/*.sql
2019-11-11 18:23:10 [INFO]  localhost:/var/run/mysqld/mysqld.sock Auth: No differences found

2019-11-11 18:23:10 [INFO]  Generating diff of localhost:/var/run/mysqld/mysqld.sock Cdr vs /root/database/localhost/Cdr/*.sql
-- instance: localhost:/var/run/mysqld/mysqld.sock
USE `Cdr`;
DROP TABLE `__EFMigrationsHistory`;
2019-11-11 18:23:10 [INFO]  localhost:/var/run/mysqld/mysqld.sock Cdr: diff complete

2019-11-11 18:23:10 [INFO]  Generating diff of localhost:/var/run/mysqld/mysqld.sock Hangfire vs /root/database/localhost/Hangfire/*.sql
2019-11-11 18:23:10 [INFO]  localhost:/var/run/mysqld/mysqld.sock Hangfire: No differences found

2019-11-11 18:23:10 [ERROR] Skipped 1 operation due to error

**Comment by VasuInukollu** [comment]
Both diff and push have problems connecting. However pull works fine without any signs of an error.

**Comment by evanelias** [comment]
Thank you for the issue report.

> the socket file discovery is not happening

There's actually no automatic discovery of the socket file. Skeema defaults to `/tmp/mysql.sock` as this is the baseline default in both [MySQL](https://dev.mysql.com/doc/refman/8.0/en/server-options.html#option_mysqld_socket) and [MariaDB](https://mariadb.com/kb/en/library/server-system-variables/#socket).

Linux distributions tend to package MySQL / MariaDB with config files which change the value for both the client and server. For example with MariaDB on Ubuntu, see the cnf files in /etc/mysql/mariadb.conf.d.  That's how the `mysql` client is able to find the socket "automatically" on your machine despite its nonstandard location.

That said, Skeema could be smarter about trying several common locations if the default one isn't found. I'll create a separate feature request issue to track this momentarily.

> Results are not consistent when using socket.

I've tried to reproduce this using your exact same version of Ubuntu and MariaDB in a virtualized environment, but so far haven't been able to trigger this error. An i/o timeout on a Unix Domain Socket seems very strange. A few questions to help debug:

* What version of Skeema are you using? (output of `skeema --version`)
* Aside from overriding the socket location, have you manually configured anything in your .skeema file(s)?
* Have you changed any connection-related configuration in MariaDB server, such as wait_timeout or max_connections?
* If you're able to do this safely, please try restarting the MariaDB server and see if the issue still persists after restarting?
* Is the error always with that same dir /root/database/localhost/Xema or is it random/inconsistent? If it's always that one, is there anything unusual about it, for example a very high number of tables present?

**Comment by evanelias** [comment]
> [mysql] 2019/11/11 18:23:05 packets.go:36: read unix @->/var/run/mysqld/mysqld.sock: i/o timeout

On closer inspection, I believe this is actually completely unrelated to use of `socket` and is instead just a query timeout. In other words, some query that Skeema is running is taking over 5 seconds in your environment. To confirm:

* For Skeema's configuration, instead of using `socket` and `host=localhost`, try using `host=127.0.0.1` to force use of tcp/ip instead of a unix domain socket. I suspect you'll still get the same error behavior.
*  For Skeema's configuration, try using `connect-options="readTimeout=30s"` to increase Skeema's query timeout to 30 seconds. I suspect it will now work properly, but it will just be slow.

Ideally I'd like to determine which Skeema query is performing slowly in your environment. You might be able to see this by running `SHOW PROCESSLIST;` in mariadb while Skeema is running, but that requires careful timing and possibly several tries to ensure you're catching the right consistently-slow query.

Another method is to enable the database's [slow query log](https://mariadb.com/kb/en/library/slow-query-log-overview/) feature. For example in mariadb you could run `SET GLOBAL slow_query_log=ON; SET GLOBAL long_query_time=4.0;` to enable the log and set it to 4 seconds, and then check the slow log file to see. Thanks!

**Comment by evanelias** [comment]
Closing due to lack of response. In any case, today's release of [Skeema v1.4.0](https://github.com/skeema/skeema/releases/tag/v1.4.0) increases the default query timeouts, which may help with whatever the problem was here.
