### ISSUE TITLE
Lint reports FULLTEXT and BTREE indexes as functionally identical

### ISSUE THREAD

**Issue by thinQ-skeema** [skeema/skeema#110]
Using skeema from release v1.3.1 on a sample table:
```
CREATE TABLE `duplicate_index` (
  `id` INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  `title` varchar(200) NOT NULL DEFAULT '',
  `data` text,
  KEY `ix_title` (`title`),
  FULLTEXT KEY `ft_title` (`title`)
) ENGINE=InnoDB;
```
results in the following skeema lint warning:
```
2019-11-14 15:58:16 [WARN]  /Users/skeema/test/duplicate_index.sql:7: Indexes ft_title and ix_title of table
                            duplicate_index are functionally identical.
                            One of them should be dropped. Redundant indexes waste disk space, and harm write performance.
``` 
However, the FULLTEXT and BTREE  indexes are not functionally identical.

**Comment by evanelias** [comment]
Good catch! Thank you for the report. In staring at the code for this I also spotted a couple other FULLTEXT-related bugs. I'll aim to put a fix in master branch tomorrow.

**Comment by thinQ-skeema** [comment]
Thank you for the fast fix - now skeema lint works as expected.

**Comment by evanelias** [comment]
Today's release of [Skeema v1.4.0](https://github.com/skeema/skeema/releases/tag/v1.4.0) includes this fix. Thanks again for the issue report!
