### ISSUE TITLE
Detecting bad partitioning

### ISSUE THREAD

**Issue by VirtualHealth-skeema** [skeema/skeema#111]
I tried skeema version 1.4.0-partition-beta1 on a test database with two tables:
```
CREATE TABLE `single_partition` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARACTER SET latin1 PARTITION BY KEY (id);

CREATE TABLE `two_partitions` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARACTER SET latin1 PARTITION BY KEY (id) PARTITIONS 2;
```
with .skeema having:
```
[production]
schema=test
flavor=percona:5.7
host=127.0.0.1
port=3306
user=root
password=***
partitioning=remove
```
The lint command reports no problems:
```
skeema lint        
2019-11-18 14:43:17 [INFO]  Linting /Users/skeema/test
```
while the diff command reports:
```
skeema diff --debug
2019-11-18 14:41:43 [INFO]  Generating diff of 127.0.0.1:3306 test vs /Users/skeema/test/*.sql
2019-11-18 14:41:43 [WARN]  Skipping table `single_partition`: unable to generate DDL due to use of unsupported features. Use --debug for more information.
-- instance: 127.0.0.1:3306
USE `test`;
ALTER TABLE `two_partitions` REMOVE PARTITIONING;
2019-11-18 14:41:43 [INFO]  127.0.0.1:3306 test: diff complete
                            
2019-11-18 14:41:43 [WARN]  Skipped 1 operation due to unsupported feature
2019-11-18 14:41:43 [DEBUG] Exit code 1
```
Note that the table with two partitions processed as expected, while the table with single partition apparently not supported. Since the table with single partition makes little sense, I suggest to detect such issue during linting and, when found, propose removal of the single partition like:
```
ALTER TABLE `single_partition` REMOVE PARTITIONING;
```

**Comment by evanelias** [comment]
Thank you for the issue report. I'll fix the bug with the unsupported diff if no partition count was supplied originally. The root cause is that `SHOW CREATE TABLE` reflects this situation differently than having an explicit `PARTITIONS 1` clause, even though the table structure is identical in both cases.

Regarding a linter rule for catching tables with only 1 partition, I'm going to hold off on that for now. Skeema does not yet manage partition *count* manipulations anyway, so having a linter rule specifically related to partition counts seems premature.

**Comment by VirtualHealth-skeema** [comment]
Thanks for the fix! Now diff command works as expected:
```
skeema diff        
2019-11-21 21:30:30 [INFO]  Generating diff of 127.0.0.1:3306 test vs /Users/skeema/test/*.sql
-- instance: 127.0.0.1:3306
USE `test`;
ALTER TABLE `single_partition` REMOVE PARTITIONING;
ALTER TABLE `two_partitions` REMOVE PARTITIONING;
2019-11-21 21:30:30 [INFO]  127.0.0.1:3306 test: diff complete
```
