### ISSUE TITLE
Referencing skeema migrations

### ISSUE THREAD

**Issue by carlosfunk** [skeema/skeema#112]
Hi,

I'm investigating skeema as an option to manage migrations for a database that is shared by multiple projects.  I'm looking for some advice or best practice examples of how you would reference a skeema migration from a different code base? 

e.g if I add a field using skeema, and then add code to a repo that depends on it, I need that migration applied before my code will work.  What is best practice here to reference that migration?

Thanks!

Carl

**Comment by evanelias** [comment]
Skeema uses an infrastructure-as-code approach -- each set of schema changes is one or more commits. So the answer depends a bit on your chosen source code management platform and deployment system. For example if you use GitHub, ideally you'd wrap each set of related schema changes in a pull request, and go through [automated CI linting](https://www.skeema.io/ci), team code review, etc. The pull request would get merged *prior* to anyone running `skeema push`.

Discussion about the status of the schema change push would occur in that same schema repo pull request, either manually (e.g. an engineer commenting when the operation has started and completed) or through custom automation (having a bot auto-comment, or using something like the GitHub deploy status API).

Meanwhile over in the related application/project pull request, you could then just link to the URL of the required schema repo pull request or individual commits. In theory it's possible to automate this further using a custom CI/CD setup which blocks merge of the application PR until the schema change has completed.

Let me know if that fully answers your question? Thanks for checking out Skeema!
