### ISSUE TITLE
Can the ignore-table option be used to exclude multiple regex patterns?

### ISSUE THREAD

**Issue by seanbrumwell** [skeema/skeema#114]
Perhaps I haven't figured it out yet, but is it possible to pass in multiple ignore-table settings in the .skeema config file?

We are working on implementing Skeema as a replacement for our old ORM based management system, however through the years we have accumulated multiple tables that have been renamed or archived that differ by client.  I'd like to create a master list of these named patterns and just have Skeema completely ignore them all completely.

For example, we have tables withe names like:
dupes_xxxx_yyyy
z_archived_xxxx_yyyy
old_xxxx_yyyy

I'd love to be able to list all of these patterns in the .skeema file, however various attempts I have made do not seem to work.  Is this supported, and if so could someone provide and example?

**Comment by evanelias** [comment]
Thanks for using Skeema! Currently you can only supply a single regex, but you may be able to accomplish your goal using the | operator in that regex. For example,
```ini
ignore-table=^(dupes|z_archived|old)_
```
will ignore any table beginning with "dupes_", "z_archived_", or "old_". Does that help, or do you end up with an excessively long regex if using that approach?

If you have multiple schemas and want to maintain just a single global ignore regex, you can put this in a top-level .skeema file. Alternatively, if you want to maintain separate ignore regexes for various hosts or schemas, you can put a different ignore-table value in each subdir's .skeema file.

**Comment by seanbrumwell** [comment]
Ah, thank you, as you can probably tell regex is not one of my strengths.  This approach should keep it manageable.  Thank you very much for the assistance!
