### ISSUE TITLE
Is there an option to ignore a directory, so skeema does not process sql file it contains.

### ISSUE THREAD

**Issue by McDeCoderDude** [skeema/skeema#115]
Is there currently an option to have skeema ignore an entire directory so, that the sql files that are contained are not processed.?

**Comment by evanelias** [comment]
Not currently, but there may be a work-around to accomplish the same thing. Can you describe your use-case a bit more, in terms of what other dirs are present and when/why you need to skip them? e.g. does it depend on the environment, or just certain commands; or are the extra dirs for use in other tools besides Skeema, etc. Thanks!

**Comment by McDeCoderDude** [comment]
Yes currently we have extra directories at the same level as our schema directory that we to store our transition scripts to setup seed data, functions and stored procedure. When we originally put together our process skeema did not support stored procedures. The files contained in the directories are versioned and get ran in sequence in new environments after we run the skeema push command against that new environment.

**Comment by evanelias** [comment]
Makes sense, thanks!

By same level, I assume you mean it's a sibling dir (same parent) to the schema directory, and not a subdir of the schema directory, correct?  If so, the easiest solution might be to just manipulate the current working directory (via `cd`) prior to running `skeema push`.

For background, most Skeema commands (including push) operate recursively from the current working directory. So one option is to only run `skeema push` after `cd`ing to a leaf directory (e.g. bottom-level dir containing *.sql and a .skeema file defining a schema name). That may be awkward/annoying if you have multiple database schemas per mysqld, but could be scriptable: for each leaf dir, `cd` and do a separate `skeema push`.

Another option might be to move the non-Skeema dir to a higher level in the directory hierarchy. That may be non-ideal though if you have multiple hosts/clusters and want to associate different seed data with each one.

**Comment by evanelias** [comment]
I should also mention -- if you haven't already, I'd recommend moving the stored procs and funcs into Skeema's dir structure. Easiest way might be to do a `skeema pull` one time after setting up a new instance. Then your non-Skeema dir will probably only contain a bunch of `INSERT` statements to manage seed data, if I understand your use-case correctly. Skeema commands will ignore `INSERT` statements (aside from some logging about them), so it would be harmless to keep those in place, as long as you don't mind the extra logging.

**Comment by evanelias** [comment]
Just wanted to follow up -- do those work-arounds help in your use-case, or should this issue be converted to a feature request? Thanks!

**Comment by McDeCoderDude** [comment]
Yes the options for work around will work for my use case. Currently we are just executing skeema from project sub directory so our transition scripts are not being parsed by skeema. There are plans later to bring our stored procedures and function into the mix so we won't have to worry about executing from the sub directory. Sorry for late reply. Thanks for your input...
