### ISSUE TITLE
Please support Postgres

### ISSUE THREAD

**Issue by bionicles** [skeema/skeema#116]
To version-control the schema as a startup founder I want to use Skeema with Postgres because MySQL has the GPL viral copyleft license which I'm concerned about using

How hard would it be to get Skeema working with PostgreSQL? It's such a great concept, I just don't like the MySQL license

**Comment by evanelias** [comment]
Thanks for reaching out. Sorry to say this would require a substantial amount of effort, and won't be practical within the near future.

**Comment by bionicles** [comment]
NP, thanks for the response

**Comment by mleonhard** [comment]
@bionicles Did you find any tool like Skeema for Postgres?  I've been using Flyway, but it has no diff function.  I'm thinking of using [migra](https://github.com/djrobstep/migra) ([HN discussion](https://news.ycombinator.com/item?id=16673526)).
