### ISSUE TITLE
Ignore table option

### ISSUE THREAD

**Issue by tomkrouper** [skeema/skeema#12]
Tools like `gh-ost` and `pt-online-schema-change` have the option to leave behind tables that start with `_`. Skeema will pick up these tables as needing to be in the schema files. I was hoping a feature could be added where you could have an option to exclude a table pattern. Something like `--ignore-table-regex="^_.*"`.

**Comment by evanelias** [comment]
Definitely prioritizing this one highly, since I've had a few people ask about it. Ditto with ignoring database schemas. Hope to knock out both sometime soon, should be fairly straightforward 🤞

**Comment by tomkrouper** [comment]
@evanelias, I've taking some golang training, and would love to attempt a PR on this. I was hoping for a little guidance though. Let me know if I'm thinking in the right direction on this.

I was thinking we could have something like this for schemas: `skeema init --ignore-schema="^test.*" -h ...`. So `--ignore-schema` would take a regex that would then be written to `.skeema` at the host level. The other commands could use the `.skeema` info to ignore the schemas.

`--ignore-table` might be a little more tricky. For my use case, having it on a host level makes total sense, I just want to ignore `^_.*` gh-ost/pt-osc tables, but I could see people wanting different tables ignored at a schema level. This might just be a documentation issue to allow `--ignore-table` globally and document how to change it to work on a schema level. I open to other ideas.

What are your thoughts?

**Comment by evanelias** [comment]
Awesome, that sounds like exactly the right approach to me! The easiest way would be to have these both be coded as global options. Typically they'd only supplied on the command-line for `skeema init` (which should propagate the values to the host-level `.skeema`, as you proposed) and then the other commands would just use the values in the option file. But no harm in allowing the user to override on the CLI for other commands too, which is how global options work by default in [mybase](https://github.com/skeema/mybase) anyway.

Sorry I've been MIA, btw. Aiming to be able to devote some time and energy to skeema again in the near future.

**Comment by tomkrouper** [comment]
With PR https://github.com/skeema/skeema/pull/15 merged, this can be closed.
