### ISSUE TITLE
I want to be able to swap out the schema on the CLI to create test instances

### ISSUE THREAD

**Issue by quietgopher** [skeema/skeema#126]
Hi!  This is a feature request.  I'm guessing there might even be a cleaner way of doing this.

I have a test suite that runs a bunch of tests against a single MySQL instance.  I create a new schema for each group of sequential tests.  I'd like to use skeema to create these tests environments based on the local skeema.

My short term hack involves copying the skeema directory and then modifying .skeema.

**Comment by quietgopher** [comment]
E.g. I want to be able to run something like `skeema push --schema mydbtest12312421` and have it populate my test instance (assuming the skeema environment is setup to hit the test instance).

**Comment by evanelias** [comment]
You can set the `schema` option in the .skeema file to [execute a command](https://github.com/skeema/skeema/blob/master/doc/options.md#schema) to determine the schema name. For a simple example using ENV vars, you could make .skeema include a line like:
```
[test]
host=127.0.0.1
schema=`echo $TEST_DB_NAME`
```
and then e.g. you can invoke `TEST_DB_NAME=mydbtest12312421 skeema push test`, or more likely set TEST_DB_NAME via an earlier step of your test suite.

**Comment by quietgopher** [comment]
Oh cool, I'll try that tomorrow.  Thanks!

**Comment by quietgopher** [comment]
Sorry.  I'm going to switch away from Skeema.  I learned that views and triggers are not supported (which are used in common db refactoring techniques).  Thank you for taking the time to reply to feature request.

**Comment by evanelias** [comment]
Support for views and/or triggers could certainly be added if a company wants to sponsor the development time. They just haven't been implemented yet because they aren't very widely used among larger MySQL-based companies.

**Comment by quietgopher** [comment]
How would you recommend doing more advanced table refactorings like
splitting a table without views and/or triggers?

**Comment by evanelias** [comment]
There are several techniques for doing this. Apologies but this topic is unrelated to Skeema and I cannot provide MySQL consulting services for free, as MySQL consulting is what I do for a living.

**Comment by quietgopher** [comment]
No worries.  Good to know.  I'll reach out to info@indexhint.com for more
info on consulting.

I prototyped sqitch and flyway and it's pretty easy to migrate from skeema
to those later.  skeema is a lot nicer for my current schema.  I'll start
with skeema and possibly switch away if I need to.
