### ISSUE TITLE
hitting "Unable to lock temporary schema on localhost:3306: Unable to acquire lock" when running a bunch of skeema locally

### ISSUE THREAD

**Issue by quietgopher** [skeema/skeema#127]
Hi.  I have about 20 tests that run against the same mysql instance and I'm using skeema to create the databases during the test runs.  The skeema directories are automatically generated with unique database strings.  I played around with a bunch of the options.  I keep getting a lock error and I do not know why.

Vague Steps:
1) Each test creates a similar schema to /tmp/mytest_{rand} with a unique db name.
2) Then I run `skeema push -pmypassword --alter-lock none`.  // I've tried with other arguments too.

Skipping /tmp/mytest_e571efa2_aa94_3e59_7663_dbbeaf96c129: Unable to lock temporary schema on localhost:33060: Unable to acquire lock

**Comment by evanelias** [comment]
Are you running multiple copies of `skeema` concurrently?

If you can provide more of the test script and complete output, this will be easier to diagnose.

**Comment by quietgopher** [comment]
Thanks for the quick reply!

Multiple calls to the skeema command line could be happening at the same time against the mysql docker instance (with different tables internally).

The whole test code is pretty large and complex to setup (needs 4 servers running and data populated).   I can copy the most revelant part below.  Each xxx.jest.js calls the following function to setup a db and tables.


```
exports.createDatabaseAndTables = async () => {
  const testDbName = `mytest_${guidGenerator()}`;

  let knex = knexCreator(connectionSpecs.testing);

  let createDbSql = (
    await fs.readFile('createdb.sql')
  ).toString();
  createDbSql = createDbSql.replace(/<db>/g, testDbName);
  await knex.raw(createDbSql);

  knex.database = testDbName;
  const dbConnectionSpec = { ...connectionSpecs.testing };
  dbConnectionSpec.connection = { ...dbConnectionSpec.connection };
  dbConnectionSpec.connection.database = testDbName;
  knex.destroy();
  knex = knexCreator(toKnexOptions(dbConnectionSpec));

  // This copies the skeema files over to tmp and replaces the db name in .skeema.
  const createTables = `cp -r ../schema/mysql/schema/local /tmp/${testDbName};
  sed -i '' s/mydb/${testDbName}/g /tmp/${testDbName}/.skeema;
  cd /tmp/${testDbName}; skeema push -pmypassword`;
  logResults(await exec(createTables));

  return {
    knex,
    testDbName,
  };
};
```

**Comment by evanelias** [comment]
> Multiple calls to the skeema command line could be happening at the same time against the mysql docker instance (with different tables internally).

If you have multiple copies of `skeema` running concurrently against the same mysql server, each invocation needs a different [temp-schema](https://github.com/skeema/skeema/blob/master/doc/options.md#temp-schema) name on the command-line. Skeema actually executes the CREATE statements from your *.sql files in a temporary location, and if you're running several copies at once, you need to ensure each copy uses a different location for this.
