### ISSUE TITLE
character set and collation

### ISSUE THREAD

**Issue by cabana1** [skeema/skeema#129]
Helllo!

I'm looking at running Skeema init on my production, development, qa, and docker environments.  
However, i'm running into issues with Skeema init and Skeema Diff.

Ideally i'd like to compare environments as they are configured, without extra checks and without changing the character set and collation.  

Skeema Init writes my table character set:  ie. 'DEFAULT CHARSET=utf8;' but excluded collation.
Skeema Diff wants to change my database, table, etc. to use the default character set and collation from the .skeema file. 

For example, here a few lines from the diff file (names scrubbed):
ALTER DATABASE `dbname1` CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `tablename1` DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci;

However I don't want these changed.
Ideally I'd like just compare and diff the environments as is.

Is this something that can be done or added?

Thanks!

**Comment by evanelias** [comment]
`skeema init` populates files using exactly the same character set and collation of the database you point it to. In other words, if you originally point `skeema init` at production, your .skeema files will be populated with the default charset and collation of your production database, and your .sql files will be populated with the default charset and collation of each table.

Are your environments using different default charset/collation than each other? For example, if you examine `SHOW CREATE DATABASE dbname1` and `SHOW CREATE TABLE dbname1.tablename1` in each environment, are the charsets/collations currently different across environments?

> Ideally i'd like to compare environments as they are configured, without extra checks
> Ideally I'd like just compare and diff the environments as is.

Afraid I don't follow. Can you please clarify what you mean by "as they are configured", "without extra checks", and "as is"? 

Dump-based commands (`skeema init`, `skeema pull`) populate the filesystem using what you have in the database environment that Skeema is pointed at. Diff-based commands (`skeema diff`, `skeema push`) do the opposite, calculating the necessary DDL to make the database look like the filesystem. Skeema does not arbitrarily introduce changes related to charset/collation, it just uses whatever is in your db already or whatever is in your filesystem.

**Comment by evanelias** [comment]
No response, closing.
