### ISSUE TITLE
Instance options settings

### ISSUE THREAD

**Issue by bzivyon** [skeema/skeema#136]
Is there a way to edit settings under `[mysqld]`
I've seen what's written [here](https://github.com/skeema/skeema/blob/master/doc/options.md#my-cnf)
But in every way I tried, I got an error: _Unknown option_
The value I would like to change is `lower_case_table_names=2`
Thanks

**Comment by evanelias** [comment]
I'm sorry but I don't understand your question. `lower_case_table_names` is a MySQL server option, and a global read-only one at that. There is no `lower_case_table_names` option in Skeema, and you generally shouldn't have a `[mysqld]` section in .skeema files, nor in the user-level MySQL config file `~/.my.cnf` either. The option you've linked to controls whether or not Skeema obtains auth options (like `user` and `password`) from `~/.my.cnf`.

Can you please describe in more detail what you're trying to do?

**Comment by bzivyon** [comment]
Makes sense
I just wanted to make sure there were no other options I didn't know about
Thanks anyway
