### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by estahn** [skeema/skeema#139]
It would be great to simplify the installation via `brew install skeema/skeema/skeema`.

[GoReleaser](https://github.com/goreleaser/goreleaser) supports the generation/update of the homebrew tap. Ther is also a [GitHub action](https://github.com/marketplace/actions/goreleaser-action) available to easily integrate.

Would you be open for a PR?

**Comment by evanelias** [comment]
I've actually never used Homebrew and am not familiar with how taps work, but I would be happy to merge a PR, thanks! Ideally with a quick tutorial on how to confirm it's working :) Skeema already uses the GoReleaser GitHub action, so hopefully it should be easy to enable the Homebrew support.
