### ISSUE TITLE
Windows build also needed

### ISSUE THREAD

**Issue by Sumit-Chakole** [skeema/skeema#14]
This is a great tool, may you build windows build too.

**Comment by evanelias** [comment]
Thanks for trying out Skeema. Sorry but I do not have a Windows system to test on. Pull requests welcome though if you find issues compiling it on Windows!

**Comment by mbrevda** [comment]
as a temporary workaround, would you consider publishing a docker image? That would make it much simpler for multi-os teams by allowing them to invoke skeema with a single binary/command (see usage below). Additionally (as long you keep the file up to date via CI/CD or manually) the image would always contain the latest binary.

Here is a straightforward dockerfile:

```docker
FROM alpine:latest

ARG SKEEMA_LIB=https://github.com/skeema/skeema
ARG SKEEMA_VERSION=1.4.3
ENV SKEEMA_URL=${SKEEMA_LIB}/releases/download/v${SKEEMA_VERSION}/
ENV SKEEMA_PACKAGE=skeema_${SKEEMA_VERSION}_linux_amd64.tar.gz
ENV SKEEMA_BIN=skeema

RUN wget -O - ${SKEEMA_URL}${SKEEMA_PACKAGE} | \
    tar -xzf - $SKEEMA_BIN -C /usr/local/bin

WORKDIR /data/schema/${DB_NAME}/

ENTRYPOINT ["skeema"]
```

If built like `docker build -t skeema` can then be invoked with `docker run --rm -it --init -v $PWD:/data skeema`. To use a db located on the host, add `-h host.docker.internal`

**Comment by evanelias** [comment]
Thanks @mbrevda, but I am hesitant to officially recommend running Skeema in a Docker container, as this greatly complicates Skeema's own [Docker-related features](https://github.com/skeema/skeema/blob/master/doc/options.md#workspace).

Have you tried using the Linux binary on Windows via WSL? I have heard this may work fine.

**Comment by mbrevda** [comment]
Oh, I see. Windows is pretty locked down at this org and it's hard to get pretty much anything that requires admin perms installed. Mac count their blessings! But for everyone else on windows, it would be good if a simpler solution could be found.

> Sorry but I do not have a Windows system to test on

Perhaps you can take advantage of CI/CD's windows support?

**Comment by evanelias** [comment]
> Perhaps you can take advantage of CI/CD's windows support?

This is a very time-consuming manner of development, and not particularly pleasant. There are a number of code paths that need to be fixed to support Windows, and doing this properly will require a local Windows machine. CI/CD will also be needed on an ongoing basis to confirm there are no regressions in future releases. However, multi-platform CI/CD providers understandably tend to limit the amount of free runtime for commercial OS's, so this will have an ongoing financial cost.

The most likely solution will be a commercial-only Windows build in 6-12 months.

**Comment by mbrevda** [comment]
>not particularly pleasant

Agreed.

> tend to limit the amount of free runtime for commercial OS's

It doesn't seem like [GitHub Actions](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions) limits build time of Open Source project

> doing this properly will require a local Windows machine

Understood. I hope you find a way sooner!

**Comment by evanelias** [comment]
> It doesn't seem like GitHub Actions limits build time of Open Source project

At this point, the Windows build of Skeema will not be free software. Please understand that Skeema is not funded by a corporation or VC firm. I am not inclined to spend my own time and money building free software for a commercial operating system that I do not personally use.

> Understood. I hope you find a way sooner!

Just to set expectations appropriately, a faster solution is extremely unlikely. This issue has been open for 2.5 years, and so far no third party has attempted a pull request for Windows support in an open source manner, nor has any corporation wanted to sponsor this development time as open source. So, the commercial software route appears to be the only remaining solution. However a Windows build is not at the top of the list of most-requested commercial features, so 6-12 months is the timeframe for that at best.

**Comment by evanelias** [comment]
A native Windows port is now complete. It will be available as part of the upcoming premium edition of the Skeema CLI in a few weeks, alongside other feature additions like views and triggers. Interested users can sign up to be [notified on launch day](https://www.skeema.io/premiumcli/?ref=windows).

If any Windows users would like an early preview, I'd be happy to add a couple Windows-based companies to the beta tester pool next week. Skeema's full integration suite now passes on Windows 10, so the core logic is all solid; but mainly I'd just like to get more feedback on Windows-isms such as config file locations, handling of options that shell out to external processes (e.g. [alter-wrapper](https://www.skeema.io/docs/options/#alter-wrapper)), etc.

If your company is interested in joining the beta, please fill out the [launch notification form](https://www.skeema.io/premiumcli/?ref=windows) and mention the beta in the comments. Thanks!

**Comment by evanelias** [comment]
I'm happy to announce that the Premium edition of the Skeema CLI, including a native Windows exe build, is now available! Learn more at the [feature comparison chart](https://www.skeema.io/download/) and [launch blog post](https://www.skeema.io/blog/2021/07/01/premium-cli/).
