### ISSUE TITLE
Option to strip DEFINER clauses from CREATEs

### ISSUE THREAD

**Issue by scoobs76** [skeema/skeema#146]
Does skeema support DDL with the definer statements removed?  Thanks

**Comment by evanelias** [comment]
You can manually write `CREATE PROCEDURE` and `CREATE FUNCTION` statements without `DEFINER` clauses in your *.sql files, and these will work fine in `skeema diff` / `skeema push`. However, MySQL interprets these to be the same as if you had included a `DEFINER` equal to the current user (i.e. the user Skeema is configured to connect as).

Every stored routine inherently has some definer in MySQL. If you wish to manage stored procedures / functions that use a different `DEFINER` than Skeema's user, `SUPER` privileges may be necessary for Skeema's user.

Does that answer your question? Or are you interested in *stripping out* the existing definers when exporting CREATEs to the filesystem via `skeema init` or `skeema pull`? That isn't supported yet, but I could see it being a useful feature request if so.

**Comment by scoobs76** [comment]
Thanks Evan. That answered my question. I agree that would be a nice future enhancement.  Thanks

**Comment by evanelias** [comment]
Awesome, glad to hear! Converting this issue into a feature request to track: I'd envision this as a `strip-definers` option which omits `DEFINER` clauses from the filesystem *.sql files. This can be useful in situations where developers each have their own non-root MySQL user, or in situations where each environment has different administrative users.

**Comment by clynch-inflexion** [comment]
Id like to second the request for a "strip-definers" option.  Im attempting to keep 4 different environments in sync and this is my remaining hurdle to being able to use skeema for the process.

**Comment by clynch-inflexion** [comment]
I could use this functionality as well.  Looking at source it looks like one could emulate include-auto-inc (ParseCreateAutoInc) to skip any diff of definers as well as to omit from *.sql files.

**Comment by evanelias** [comment]
Part of the complexity is that this would also affect views and triggers, but those aren't supported in the community edition of Skeema. Most likely this feature will be added to the premium products in a few months.

Sorry but it won't be practical to maintain a proc/func-only alternative implementation of this feature just in the open source edition.

**Comment by evanelias** [comment]
I'm happy to announce that the new [strip-definer](https://www.skeema.io/docs/options/#strip-definer) option is now available in today's release of [Skeema Premium CLI v1.6.0](https://www.skeema.io/download/)! When enabled, it removes DEFINER clauses from *.sql files, and ignores them in diff comparisons, for all stored procedures, functions, views, and triggers.

With default value of "auto", definer stripping is enabled automatically whenever Skeema's user does not have SUPER / SET_USER_ID permissions to override definers.

This option is designed to simplify workflows in several different situations:
* database-as-a-service platforms (RDS, Cloud SQL, etc) where SUPER privileges are not available
* situations where each environment has a different administrative user
* companies where developers each have their own non-root MySQL user
