### ISSUE TITLE
website: add live text based schema diffing

### ISSUE THREAD

**Issue by derekperkins** [skeema/skeema#153]
I think it would be useful if the website added some basic diff functionality as a way to dip your toe into skeema. I love all the things that skeema can automate, but sometimes I just want a quick and dirty alter statement generated without diving into the cli. It seems like it wouldn't be hard to add a text based diff to the website, similar to https://www.jsonschemavalidator.net/ with a few configurable options. It'd be a quick value add that is likely to attract links and introduce new users to skeema.

**Comment by evanelias** [comment]
It's a good idea (and something I've considered in the past), but realistically it would be a solid month of development and design time to implement in an efficient and secure manner, plus some ongoing hosting cost. Unfortunately it just isn't practical to provide additional free SaaS offerings at this time.

**Comment by derekperkins** [comment]
Fair enough, I was hoping that it'd be easier to implement than that, but if it has to run against a live MySQL instance, I can see how that'd be a much bigger lift.
