### ISSUE TITLE
MySQL 8 Routines not supported?

### ISSUE THREAD

**Issue by odnarb** [skeema/skeema#161]
Hello,

I just installed mysql 8 and skeema on Ubuntu 20 and it seems a `skeema init` did not pull my stored procs.

To be sure it wasn't a permissions issue I did the init with my root mysql user.

I checked the `information_schema.routines` table and the routines exist.

I tried scouring the docs, open issues, and closed issues before opening this. I apologize if I missed some config, option or issue I should have seen.

Happy to provide more information as I want to integrate this into a project's CI/CD after reading GitHub's use case article on this handy tool.

Thank you!

**Comment by evanelias** [comment]
Routines are fully supported for MySQL 8, and this should work (and is fully covered by the integration tests). But this code was recently modified a bit in Skeema 1.5, so maybe there's some rare edge-case you're hitting.

Are any errors or warnings displayed, or are the routines just silently missing from the files created by `skeema init`?

Which exact version of MySQL 8 are you using (e.g. "8.0.23")? MySQL 8 sometimes has substantial changes in point releases now, so the full version may be relevant.

If you can verify the following, it may help debug:
* If you run `SELECT routine_name, routine_type FROM information_schema.routines WHERE routine_definition IS NOT NULL AND routine_schema = 'db_name';` (replace `'db_name'` with your application db) are your expected routines all present?
* If you run `SHOW CREATE PROCEDURE` (or `SHOW CREATE FUNCTION` if a func) on any routine from the previous query, does the result match what you expect?
* What does the output of `skeema init` show? Does it create files for the tables but not the routines?

If you're able to share one of the routine bodies (SHOW CREATE output), that may also help a lot. If an end-to-end simple independent repro is possible, e.g. creating just 1 routine and then showing `skeema init` fail to obtain it, that would be ideal. Or if you need to share anything privately, please use the support address on https://github.com/skeema/ -- thanks!

> I want to integrate this into a project's CI/CD after reading GitHub's use case article

One word of caution, please note that GitHub's use-case is pretty unusual and specific to large scale. Their usage pattern is non-idiomatic and doesn't necessarily make sense for most other Skeema users. Fully automating the CD lifecycle safely is quite tricky. Even just the CI side can be complex; [Skeema Cloud Linter](https://www.skeema.io/cloud/) exists as a commercial solution to help simplify this.

**Comment by odnarb** [comment]
I apologize for not initially including the mysql version. In my haste to get this all done the other day I suspended that and some other critical thinking. These are great questions.

mysql version:
`mysql  Ver 8.0.23 for Linux on x86_64 (MySQL Community Server - GPL)`

After trying the select statement you mentioned in your first point I saw that it worked fine for the root user but not the actual user in question.

Thus I realized I was creating the procs with the root user, since this is just a local VM. I dropped the procs as the root user and re-created the procs as the app user, for example, `mytestuser`@`%` for those who might run into this.

Problem solved. Procs get dumped out.

As for your response on CI/CD, thank you. We're going to proceed with caution for the time being since we're just starting out, but will need to keep costs down. I may consider your organization in the future. I do appreciate your hard work and support for my silly question. The rest of the industry WILL reward you for this product (and db services). In the meantime do you have a link for something like a tip, donation, etc?

Another question directly related is the proc definition that gets generated (or dumped) has a definer set.
```sql
DELIMITER //
CREATE DEFINER=`mytestuser`@`localhost` PROCEDURE `myTestProc`()
BEGIN
```

Is there any way to skip this output while performing a `skeema init` ?
Or is my option left to dig into the `allow-definer` option when doing a `skeema push` ?

I'd rather not have this content in my codebase if possible.

Thank you!

**Comment by evanelias** [comment]
> After trying the select statement you mentioned in your first point I saw that it worked fine for the root user but not the actual user in question.

MySQL [restricts routine body visibility](https://dev.mysql.com/doc/refman/8.0/en/show-create-procedure.html) based on privileges and definer; the specific requirements vary by MySQL version. However, your initial post said you ran `skeema init` as root, so this situation doesn't really make sense. But in any case, I'm glad this is working now and does not appear to be a Skeema bug, so I'll close this out.

> the proc definition that gets generated (or dumped) has a definer set

Skeema currently just dumps what's shown by `SHOW CREATE` which always includes a definer. There's an open feature request to make this optional in #146.

> Or is my option left to dig into the `allow-definer` option when doing a `skeema push` ?

This option restricts which definer values are permitted; for example you could use it to ensure that procs are always created by `someuser` instead of `root`. But it does not affect the proc content in .sql files.
