### ISSUE TITLE
Support usage of internal Docker Registry

### ISSUE THREAD

**Issue by leokhachatorians** [skeema/skeema#162]
My current workplace operates in an environment where we fetch our pip/docker/npm/etc. packages from our Nexus Sonatype Repository, as such we can't use `workspace=docker` as it attempts to pull directly from Dockerhub. It would be most helpful if it was supported to specify the specific dockereg of where to pull these images from. 

I wouldn't mind helping out myself, but I'm more of a Rust guy, so I might need a bit more hand-holding on the PR process :p

**Comment by leokhachatorians** [comment]
Actually, think this is moot, Manually pulling the image myself seemed to unblock running `skeema diff` for example.

**Comment by evanelias** [comment]
I've added a few sentences to the [docs for workspace=docker](https://www.skeema.io/docs/options/#workspace) to clarify the use of DockerHub and to mention this work-around. Thanks for the issue report, I definitely agree this wasn't intuitive previously.
