### ISSUE TITLE
Skeema complains/skips tables when "USING BTREE" index clause present

### ISSUE THREAD

**Issue by ilmiont** [skeema/skeema#166]
**Describe the bug**

Skeema unexpectedly skips tables due to "unsupported features" when a SQL file on-disk contains `USING BTREE` for an index, but the corresponding table in the target database does not. As `BTREE` is the InnoDB default when no index is specified, Skeema doesn't need to do anything and in my opinion this difference in the diff should not cause the table to be skipped.

This was previously reported in #13 and then closed and reported fixed in c51eee3.

Yet it seems to be present in v1.5.2:

![image](https://user-images.githubusercontent.com/6921571/127883542-200e4001-cb4d-4b1e-9be3-f763e1e91457.png)

This is frustrating as some database management tools do include `USING BTREE` in their `CREATE TABLE` statements. PHPMyAdmin is being used in this case, which does append those clauses. The SQL files in the filesystem have it in their table definitions; the database I'm trying to `skeema push` to apparently does not, yet there are no other issues.

**Environment**

- Skeema v1.5.2, amd64 build
- - MySQL 5.7

**To Reproduce**

1. SQL file with `USING BTREE` on an index definition.
2. Push to database with table version that lacks the clause.
3. Skeema skips and complains about unsupported features.

**Expected behavior**

Skeema should not skip tables where the only diff is missing `USING BTREE` on an index definition on the push target.

**Comment by ilmiont** [comment]
Arg the offending tables are actually MyISAM - I suppose that's the culprit here?

**Comment by evanelias** [comment]
Yes, Skeema is primarily [aimed at InnoDB tables](https://www.skeema.io/docs/requirements/). All other storage engines are best-effort only.

The functionality to strip `USING BTREE` clauses works correctly for InnoDB tables, and is covered by integration tests to ensure there's no regression.

Your best bet for a work-around is to strip these clauses using automation prior to running `skeema diff` or `skeema push`. For example, you could write a small wrapper script which uses `sed`. Alternatively, you could just skip these specific tables with an [ignore-table](https://www.skeema.io/docs/options/#ignore-table) regex.

That said, use of MyISAM in 2021 is discouraged fairly universally.
