### ISSUE TITLE
Databases option for schema init

### ISSUE THREAD

**Issue by inmanturbo** [skeema/skeema#167]
Option to allow for extracting specific schema from database instance, rather than **all** schemas

**Comment by inmanturbo** [comment]
aah I see,can use `--ignore-schema` option

**Comment by evanelias** [comment]
If you just want a single schema, use the [--schema](https://www.skeema.io/docs/options/#schema) option. This is mentioned in the --help text for [`skeema init`](https://www.skeema.io/docs/commands/init/).

**Comment by inmanturbo** [comment]
@evanelias thanks!
