### ISSUE TITLE
Alter table with drop and add instead of 

### ISSUE THREAD

**Issue by stian90** [skeema/skeema#180]
**Describe the bug**
*A clear and concise description of what the bug is.* 

When changing a table row name from "test" to "test2" and running skeema diff, the suggested command from skeema is "ALTER TABLE `test` DROP COLUMN `test`, ADD COLUMN `test2` int NOT NULL" 

This is not allowed unless you you --allow-unsafe, witch is a good thing as it will delete all data in "test" row. and insert a new empty test2 row. 

This could be avoided if skeema detected that this is a name change, and instead run the command "ALTER TABLE `test`
CHANGE `test2` `test` int NOT NULL AFTER `id`;" 

Is there a reason for not doing it this way? 

**Environment**
- Skeema version: *[e.g. v1.5.0]*
- Database vendor, version, OS/platform: *[e.g. MySQL 8.0.23 running on Linux]*
- Any other environmental notes or special configuration:

skeema version 1.6.0-community, commit 9a41f4d8c42689ccec6f4a8b98930f37f00f40df, released 2021-11-11T20:54:11Z
MySQL versjon: 8.0.27 running on docker from official mysql docker. 

**To Reproduce**
*Steps to reproduce the behavior.*

edit the name of table row in .sql file and running skeema diff

**Expected behavior**
*A clear and concise description of what you expected to happen.*

Alter table with CHANGE instead of DROP and ADD. 

**Additional context**
*Add any other context about the problem here.*

**Comment by evanelias** [comment]
With declarative schema management, there is no way for the tool to automatically determine whether or not your intention is a rename. Please see https://www.skeema.io/docs/requirements/#renaming-columns-or-tables, #6, and #5.
