### ISSUE TITLE
Ability to manually edit diffs in case undesired schema is generated ? 

### ISSUE THREAD

**Issue by someshkoli** [skeema/skeema#182]
*Please refer to the Contributing link in the sidebar for guidance.*

**Comment by evanelias** [comment]
Do you have an example of what you mean by undesired schema?

With the [recommended workflow](https://www.skeema.io/docs/workflow/#schema-change-process), you should **always** review the generated DDL using [`skeema diff`](https://www.skeema.io/docs/commands/diff/) and/or [Skeema Cloud Linter for GitHub](https://www.skeema.io/docs/install/cloud/), before executing anything with [`skeema push`](https://www.skeema.io/docs/commands/push/). 

If something in the diff is undesired, you can just edit your *.sql files accordingly and then repeat the diff review process.

Skeema is an infrastructure-as-code solution, and the overall process is intended to be very similar to how you handle application code review and deployment: if you catch an issue in code review, you can add additional commits or amend your previous commits before deploying.

Some companies also choose not to use [`skeema push`](https://www.skeema.io/docs/commands/push/) directly at all. In theory you can just capture the STDOUT of [`skeema diff`](https://www.skeema.io/docs/commands/diff/) and then use that in another separate system, possibly with a manual edit step in between.
