### ISSUE TITLE
RFC: use Docker CLI instead of Docker API

### ISSUE THREAD

**Issue by evanelias** [skeema/skeema#186]
This is a proposal to adjust the mechanics of Skeema's built-in Docker interactions. If you use Skeema's [workspace=docker](https://www.skeema.io/docs/options/#workspace) option, this change could affect you. We aren't necessarily going ahead with this change soon, or at all. Community feedback will be greatly appreciated in steering the decision. 

## Background

Skeema has built-in interactions with Docker in two places:

* The [workspace=docker](https://www.skeema.io/docs/options/#workspace) option: when enabled, Skeema performs its [temporary scratch-space operations](https://www.skeema.io/docs/faq/#no-reliance-on-sql-parsing) on an ephemeral database instance in an automatically-managed Docker container, instead of using a temporary schema (e.g. _skeema_tmp) on your real DB instance. This option is recommended in high-volume production environments, as well as situations where Skeema is operating over a WAN/VPN with high network latency between `skeema` and your databases.
* Skeema's integration testing suites use Docker extensively, to perform automated end-to-end testing against all supported database vendors and versions. In combination (MySQL + Percona Server + MariaDB), each release of Skeema Community Edition is thoroughly tested against 16 different Dockerized database images.

These interactions [currently](https://github.com/skeema/skeema/blob/f9a6bb20322dd557590acea5746a906a909bba16/internal/tengo/docker.go) use Docker's API, by wrapping the third-party package [fsouza/go-dockerclient](https://github.com/fsouza/go-dockerclient). This means they interact with a local Docker socket, and do not currently require a `docker` binary to be present.

## Proposed change

Instead of using the Docker API, Skeema could shell out to the `docker` CLI, parsing JSON responses where needed (e.g. `docker inspect` output). This would require a `docker` binary to be present and in your $PATH if you wish to use [workspace=docker](https://www.skeema.io/docs/options/#workspace), or if you wish to run Skeema's integration testing suite locally.

### Fewer Golang package dependencies, smaller binaries

Although [fsouza/go-dockerclient](https://github.com/fsouza/go-dockerclient) is a very nice library, it has [quite a lot of dependencies](https://github.com/fsouza/go-dockerclient/blob/efad4e7b270dcf6d24acdbe9b6244794b99386ba/go.mod). The vast majority of these packages handle container-related functionality that Skeema does not need or use, but it nonetheless bloats Skeema's dependency graph.

These indirect dependencies frequently have security advisories, which aren't relevant to Skeema (since the affected dependency code paths are not used or accessible in Skeema), but nonetheless cause spurious Dependabot alerts from GitHub.

We expect the size of the `skeema` binary could be reduced by over 25% just from the removal of [fsouza/go-dockerclient](https://github.com/fsouza/go-dockerclient) and its dependencies.

### Compatibility with non-Docker container systems (e.g. `podman`)

Podman is gaining popularity as a daemon-less, root-less alternative to Docker. For some use-cases, it can serve as a drop-in replacement for the `docker` binary.

Although Podman also offers an optional network-accessible API, using it negates some of Podman's benefits. Switching Skeema's Docker interactions to use the `docker` binary should provide a better path for users who wish to substitute in a `podman` binary, or any other Docker-compatible binary.

### Future feature integrations

Improvements in Skeema's shellout logic could be leveraged in the Docker CLI interaction code. For example, Skeema Premium CLI includes extensive [SSH integration](https://www.skeema.io/docs/options/#ssh). Hypothetically, this could be used to enable secure execution of `docker` commands on a remote host, alongside an automatic SSH tunnel to reach the ephemeral containerized database -- without even needing to expose either the Docker daemon or the containerized database outside of localhost on the remote host.

## Potential drawbacks

Some users enable [workspace=docker](https://www.skeema.io/docs/options/#workspace) while also running `skeema` itself inside Docker. This configuration is already a bit difficult -- it requires either bind-mounting the Docker socket into Skeema's container, or using a special Docker-in-Docker image. See #89 for more background.

If the change proposed in this RFC is implemented, such a configuration would become slightly more difficult: in addition to bind-mounting the Docker socket into Skeema's container, you would *also* need to install the Docker CLI inside Skeema's container, using your base image’s packaging system. (Although bind-mounting works for the Docker *socket*, bind-mounting the `docker` *binary* is not recommended, as this reportedly does not function properly.)

If you use this type of configuration, we'd love to hear your thoughts on this proposal and get a better sense of whether this would be too disruptive of a change.

**Comment by tspotts** [comment]
Would the official Docker golang SDK be a little more lightweight? 
https://docs.docker.com/engine/api/sdk/

It also looks like you can now interact with the Docker API over HTTP 🤔

**Comment by evanelias** [comment]
It's a good suggestion, but the official docker golang SDK still doesn't have a go.mod, so it's hard to tell easily. Historically, Docker's github repo has had a ton of open issues regarding modules and versioning, so I've always steered clear of using it directly... my impression is that the official client SDK doesn't play nice with the normal Go module ecosystem and versioning practices, and it also still brings in most of the same imports / massive dependency tree as the third-party wrapper that Skeema currently uses. 

Shelling out to the docker CLI in the future should be much more lightweight, so that's still the direction I'm leaning in. Is your concern regarding Docker-in-Docker, or something else?

fwiw Skeema v1.9.0-premium introduced the [temp-schema-environment](https://www.skeema.io/docs/options/#temp-schema-environment) option, to offload Skeema workspaces to arbitrary database hosts, which tends to be a lot cleaner and more flexible than Docker-in-Docker anyway :)

**Comment by tspotts** [comment]
Yes, in my experience Docker-in-Dockerception is a nightmare fraught with all forms of perils that are best to be avoided.  `temp-schema-environment` sounds like a good option for us.

**Comment by evanelias** [comment]
This change is finally being merged to the main branch later today, and will be included in Skeema v1.11.0, with a target release date in September.

Quick recap of the implications:

* Instead of bundling a Golang Docker client implementation, Skeema's [workspace=docker](https://www.skeema.io/docs/options/#workspace) option will now simply shell out to the `docker` command-line client binary. Ditto for Skeema's integration testing suite.

* This change will only affect users who run `skeema` in a container environment (including k8s) *and* also use [workspace=docker](https://www.skeema.io/docs/options/#workspace) at the same time.
  * In this case, you will now need to ensure that Skeema's container has a `docker` cli binary available. Best practice is to obtain it from either the docker:cli image or your distribution's package manager.
  * Skeema Premium Edition users can alternatively switch to using the [temp-schema-environment](https://www.skeema.io/docs/options/#temp-schema-environment) option, to offload the workspace database to any arbitrary pre-existing database host, instead of using an ephemeral Docker container.

* Skeema community edition CLI binary size will drop by a massive **40%** as a result of removing go-dockerclient and its large dependency graph.

* Skeema premium edition CLI binary size will drop by 25%. (The reduction is *proportionally* smaller there since all the extra [premium features](https://www.skeema.io/download/) are thousands of lines of code, and the extensive [SSH tunnel](https://www.skeema.io/docs/options/#ssh) functionality in particular includes a few large dependencies.)

* This will completely prevent the frequent false-positive security warnings (picked up by Dependabot and other automation) which were caused by dependencies of the go-dockerclient package. None of these were ever "real" security problems, as the relevant code paths in the CVEs weren't actually included in go-dockerclient, let alone in Skeema. They were entirely false-positives caused by the lack of granularity of security scanners doing naive scanning on Golang go.mod files.

**Comment by evanelias** [comment]
Skeema v1.11.0 was [released today](https://www.skeema.io/blog/2023/09/26/v1110-released/) and it contains this change.
