### ISSUE TITLE
Diff not working when some options are passed

### ISSUE THREAD

**Issue by louman** [skeema/skeema#188]
**Describe the bug**
I'm trying to use skeema to compare two local databases however when I run `diff` with the flags `--allow-auto-inc` or `--allow-charset`, the command just hands and `--debug` doesn't output anything.

**Environment**
- Skeema version: 1.8.0
- Database vendor, version, OS/platform: MySQL 5.7 running on MacOS Monterrey v12.5

**To Reproduce**
Unsure if this would be easy to reproduce as it could be related to my local database.  However these are the steps I followed:

1. skeema init -h 127.0.0.1 -u root -d schemas --schema mydb
2. cd schema && skeema add-environment local --host 127.0.0.1 --port 3306
3. skeema diff --debug local 1> diff.sql

At this stage, step 3 prints:

```
2022-07-26 14:13:22 [INFO]  Generating diff of 127.0.0.1:3306 mydb vs /Users/***/Projects/skeema/schemas/*.sql
2022-07-26 14:13:51 [ERROR] Preventing execution of unsafe or potentially destructive statement:
                              # DROP TABLE `employer_student`
                            Use --allow-unsafe or --safe-below-size to permit this operation. For more information, see Safety Options section of --help.
2022-07-26 14:13:51 [WARN]  Skipping 401 additional operations for 127.0.0.1:3306 mydb due to previous error

2022-07-26 14:13:51 [ERROR] Skipped 402 operations due to problems
2022-07-26 14:13:51 [DEBUG] Exit code 2
```

I then run the same command but adding the `--allow-unsafe` option:

```
skeema diff --debug --allow-unsafe local 1> diff.sql
```
But nothing gets printed and the command just hangs until I kill it.

**Expected behavior**
The diff runs successfully

**Additional context**
I'm trying to compare a legacy database with over 600 tables and a few triggers and functions. Not sure if the issue I'm having could be related to that.

Also, I'm comparing two databases locally using a single server. What I did was restore structure A into `mydb` then I ran skeema init to generate the SQL files, then I restored structure B into the same `mydb` and then ran `skeema diff`

**Comment by louman** [comment]
Please disregard this. It turns out I didn't realise the command I was running included `-p` so the reason why it was hanging is because it was waiting for the db password to be entered 🥟

**Comment by evanelias** [comment]
I just pushed a commit c0267f4 designed to make the password prompt more user-friendly, since I'm sure others have stumbled over the same situation. The "Enter password:" text will now go to STDERR by default, instead of STDOUT, so it will still be visible even if you're redirecting STDOUT (assuming you're not also redirecting STDERR).

I'll re-title this issue momentarily to better reflect the cause.
