### ISSUE TITLE
MariaDB 10.9.4 changes `SHOW CREATE` statement

### ISSUE THREAD

**Issue by Sparticuz** [skeema/skeema#193]
**Describe the bug**
Updating to MariaDB 10.9.4 and I can no longer use skeema.
`[WARN]  Skipping table gen_territories: Skeema does not support generating a diff of this table. Use --debug to see which properties of this table are not supported.`

--debug shows the following:
```
[DEBUG] The desired state ("to" side of diff) contains unexpected or unsupported clauses in SHOW CREATE TABLE.
                            --- desired state expected CREATE
                            +++ desired state actual SHOW CREATE
                            @@ -3,2 +3,2 @@
                            -  `TerritoryName` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
                            -  `sales_rep` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                            +  `TerritoryName` varchar(45) NOT NULL,
                            +  `sales_rep` varchar(45) DEFAULT NULL,
                            @@ -6,3 +6,3 @@
                            -  `gdata_calendarid` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'This is the calendar ID for V1',
                            -  `gdata_sub` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'This is the subscriber for V2',
                            -  `gdata_access_token` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'This is the subscriber''s access toke for V2',
                            +  `gdata_calendarid` varchar(191) DEFAULT NULL COMMENT 'This is the calendar ID for V1',
                            +  `gdata_sub` varchar(191) DEFAULT NULL COMMENT 'This is the subscriber for V2',
                            +  `gdata_access_token` varchar(255) DEFAULT NULL COMMENT 'This is the subscriber''s access toke for V2',
```

**Environment**
- Skeema version: *skeema version 1.8.2-community, commit 19801326958762b461d339ddd02ce139f3eb79b0, released 2022-09-14T20:51:18Z*
- Database vendor, version, OS/platform: *MariaDB 10.9.4 (docker tag mariadb:latest)*

**To Reproduce**
Upgrade to MariaDB 10.9.4 and try to use skeema

**Expected behavior**
skeema works

**Additional context**
https://github.com/MariaDB/server/commit/0703c9ec1e
https://github.com/MariaDB/server/commit/0333ddd3ec
https://jira.mariadb.org/browse/MDEV-29446

**Comment by evanelias** [comment]
Already fixed in main branch in f2dcaf8f4 last week (and quite annoyingly time-consuming to deal with I might add), there just hasn't been a new Skeema release yet.

**Comment by Sparticuz** [comment]
Thank you

**Comment by evanelias** [comment]
Skeema v1.9.0 has now been [released](https://www.skeema.io/blog/2022/11/30/v190-released/), and contains this fix.

**Comment by evanelias** [comment]
:wave: Hi @Sparticuz – I noticed your Drizzle issue and didn't want to spam there, but just wanted to ask if you had any brief feedback on Skeema, to see if we can better meet your needs in the future.

Skeema is tested against MariaDB 10.1 through the latest GA version (currently MariaDB 11.5, soon to be 11.6) and we are very careful to handle the [numerous differences between MySQL and MariaDB](https://www.skeema.io/blog/2023/05/10/mysql-vs-mariadb-schema/) which most other schema management tools lack. Although there are a few MariaDB-specific features that we don't support yet (system-versioned tables, sequences, packages) we can definitely prioritize those based on user interest.

No pressure, but if you have a chance to share your thoughts, I'd like to get a better sense of where Skeema is falling short. Thanks!

**Comment by Sparticuz** [comment]
Hey, I'm moving to drizzle because we're migrating our stack to Nextjs and drizzle integrates nicely with our code. I do (and will continue to) use skeema for the foreseeable future until drizzle adds a bunch of functionality that I use within skeema. As well as other projects that I don't use drizzle on. imho, Skeema is one of the easiest schema management tools because it's just pure sql.
While I understand the need to charge for premium features (I also wish people would sponsor my oss, hah), the cost is way outside of our price range for a SMB, for software that I don't use enough to justify that cost...I pay less per month for the database itself... I only miss the VIEWs though, I just manage them separately, similar to skeema, with CREATE VIEW files for each view. I appreciate you @evanelias. Thank you for continuing to develop skeema.

**Comment by evanelias** [comment]
👍 thank you for the feedback!
