### ISSUE TITLE
skeema format: column collation statements removed when using mariadb:10.3.37 as flavor

### ISSUE THREAD

**Issue by markododa** [skeema/skeema#195]
Not sure if this is a skeema bug or something with mariadb.

When using flavor=mariadb:10.3.37

```
[remote]
flavor=mariadb:10.3.37
host=localhost
port=3306
user=skeema-admin
```

skeema format
```
skeema format --workspace=docker remote
```
removes the COLLATE statement from the column definitions

for example

```
-  `cron` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
-  `status` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
+  `cron` varchar(25) NOT NULL,
+  `status` varchar(10) NOT NULL,
```

this does not happen when flavor is set to mariadb:10.3.36
The behavior persists between various skeema versions, i tested the following versions

```
skeema version 1.5.2-community,
skeema version 1.8.2-community
```

**Comment by evanelias** [comment]
MariaDB changed the behavior of `SHOW CREATE TABLE` in their point releases this month (including 10.3.37), completely breaking compatibility with Skeema. Please see f2dcaf8 and #193. The next Skeema release (v1.9.0) should be out in 1-2 weeks.

**Comment by markododa** [comment]
Thank you!

**Comment by evanelias** [comment]
Skeema v1.9.0 has now been [released](https://www.skeema.io/blog/2022/11/30/v190-released/), and contains this fix.
