### ISSUE TITLE
Diff command skipping SQL Files 

### ISSUE THREAD

**Issue by Nikhileshinps** [skeema/skeema#198]
Hi,

I have few tables with partitions and some of them show me this error in diff command -
The original state ("from" side of diff) contains unexpected or unsupported clauses in SHOW CREATE TABLE.
                            --- original state expected CREATE
                            +++ original state actual SHOW CREATE
                            @@ -6 +6 @@
                            -/*!50500 PARTITION BY LIST  COLUMNS(`category`)
                            +/*!50500 PARTITION BY LIST  COLUMNS(category)

Regards,
N

**Comment by evanelias** [comment]
Please [re-file this as a "bug report"](https://github.com/skeema/skeema/issues/new?assignees=&labels=bug&template=bug_report.md&title=), rather than as a "question", and include all relevant fields from the bug report template. It's impossible to debug this without that information. Thanks!
