### ISSUE TITLE
Altering datetime defaults causes panic

### ISSUE THREAD

**Issue by rkorebrits-paystack** [skeema/skeema#227]
**Describe the bug**
I'm trying to alter a `datetime` column, that has `DEFAULT NULL` and nothing else, to have `CURRENT_TIMESTAMP` as `DEFAULT` and `ON UPDATE`.

**Environment**
- Skeema version and OS: 
  - `skeema version 1.11.1-community`
  - `commit d637ed77fa1fe1f82f8fdd982740b99f754cf2d5, released 2023-12-04T22:50:03Z`
  - Running on MacOS
- Database vendor, version, OS/platform: MySQL `5.7.12-log` (`select version();`) on RDS
- Any other environmental notes or special configuration: `ENGINE=InnoDB DEFAULT CHARSET=utf8`

**To Reproduce**
1. `skeema pull production` - No file system changes, already up to date
2. Change `updated_at datetime DEFAULT NULL,` to `updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`
3. `skeema diff production` (--debug)
  - General warnings `Docker images for mysql:5.7 are not available. Substituting`

Debug output:
```shell
2024-03-08 12:13:45 [DEBUG] goroutine 249 [running]:
                            runtime/debug.Stack()
                                /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/debug/stack.go:24 +0x64
                            main.panicHandler()
                                /home/runner/work/skeema/skeema/exit.go:150 +0x114
                            panic({0x102c40a60?, 0x102e325d0?})
                                /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x218
                            github.com/skeema/skeema/internal/applier.CreatePlanForTarget(0x14000386630,
                            0x14000384090?, {0x1, 0x2, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
                                /home/runner/work/skeema/skeema/internal/applier/applier.go:318 +0x7d0
                            github.com/skeema/skeema/internal/applier.ApplyTarget(0x14000386630, {0x102c91fb8,
                            0x14000125200})
                                /home/runner/work/skeema/skeema/internal/applier/applier.go:164 +0x4bc
                            main.PushHandler.func1()
                                /home/runner/work/skeema/skeema/cmd_push.go:121 +0xe8
                            golang.org/x/sync/errgroup.(*Group).Go.func1()
                                /home/runner/work/skeema/skeema/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0x58
                            created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
                                /home/runner/work/skeema/skeema/vendor/golang.org/x/sync/errgroup/errgroup.go:72 +0x98
                            
2024-03-08 12:13:45 [ERROR] Uncaught panic in github.com/skeema/skeema/internal/applier.CreatePlanForTarget at
                            /home/runner/work/skeema/skeema/internal/applier/applier.go:318: runtime error: invalid
                            memory address or nil pointer dereference
                            This situation indicates a bug in Skeema. Use --debug to view full stack trace.
                            Please file an issue report at https://github.com/skeema/skeema/issues with any available
                            background information.
```

**Expected behavior**
It should generate the diff

**Additional context**
Sample table

```sql
CREATE TABLE `mytable` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `field1` varchar(20) NOT NULL,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by evanelias** [comment]
This is the exact same issue you just reported in #226. Again, under these exact conditions you will get an uncaught panic:

* Target database server is running MySQL 5.7 (or anything before MySQL 8)
* Client machine is a recent Mac (Apple Silicon / ARM CPU)
* Skeema is configured to use workspace=docker
* At least one table has a column (anywhere in your schema) that uses the legacy 3-byte utf8 character set

It does not matter what is in the diff. If these conditions are true you will get a panic from `skeema diff` or `skeema push`, it's the exact same cause as already discussed in your other issue.

**Comment by rkorebrits-paystack** [comment]
Ah ok, thanks, didn't realise it was related, sorry! It's against a different database that doesn't have the `0900` collation, so I assumed it was different.
