### ISSUE TITLE
Skeema Java/Kotlin SDK?

### ISSUE THREAD

**Issue by damar-block** [skeema/skeema#228]
Are there any plans to provide SDK for running Skeema within a Java/Kotlin service?

**Comment by evanelias** [comment]
Sorry, I don't follow. Skeema isn't a library. It's single static binary. If you wish to automate its behavior, you can shell out to it from any language. See our docs on [automation](https://www.skeema.io/docs/automation/) as well as [recipes](https://www.skeema.io/docs/recipes/).

Can you please clarify what you're looking for here? Thanks.
