### ISSUE TITLE
Vitess Support

### ISSUE THREAD

**Issue by Flo4604** [skeema/skeema#230]
Currently trying to use skeema with a planetscale database running `8.0.34-Vitess` and getting the following error. 

```
2024-08-19 23:13:38 [ERROR] Skipping xxxx: Unable to fetch schema steamsets from aws.connect.psdb.cloud:3306: Error querying information_schema.routines for schema xxx: Error 1105 (HY000): syntax error at
                            position 37
``` 

I assume this is because vitess is not supported thus I was wondering if support for this is planned.

**Comment by evanelias** [comment]
Not supported as per [documentation on proxies/middleware that manipulate result sets](https://www.skeema.io/docs/requirements/), and [won't ever be implemented under any circumstances](https://github.com/skeema/skeema/issues/215).
