### ISSUE TITLE
skeema does not support sql_mode=ANSI_QUOTES

### ISSUE THREAD

**Issue by mv-steven** [skeema/skeema#31]
I built the latest version of skeema this afternoon with the command in the documentation:

`go get -u github.com/skeema/skeema`

I created a simple database, containing one table, containing one field.  I ran 'skeema init' to initialize the schema repository.  I made no changes to the files, I immediately ran 'skeema diff' and it is showing me there are differences, and when I run 'skeema push', it drops my original table and recreates it with the tablename wrapped in double quotes.  Please see below.  System information, etc. is at the bottom.

```
$ mysql << done
> create database skeematest;
> use skeematest;
> create table testtable ( id integer not null, primary key ( id ) );
> describe testtable;
> done
Field   Type    Null    Key     Default Extra
id      int(11) NO      PRI     NULL
$ skeema init -h localhost:3306 -uroot --schema skeematest
2018-07-06 15:44:45 [INFO]  Creating and using host dir /home/steven/skeema/localhost:3306 for localhost:3306; skipping schema-level subdirs

2018-07-06 15:44:45 [INFO]  Populating /home/steven/skeema/localhost:3306
2018-07-06 15:44:45 [INFO]  Wrote /home/steven/skeema/localhost:3306/testtable.sql (113 bytes)

$ skeema diff --debug --allow-unsafe
2018-07-06 15:44:52 [INFO]  Generating diff of localhost:3306 skeematest vs /home/steven/skeema/localhost:3306/*.sql
2018-07-06 15:44:52 [DEBUG] /home/steven/skeema/localhost:3306/testtable.sql: filename does not match table name of "testtable"
-- instance: localhost:3306
USE `skeematest`;
CREATE TABLE """testtable""" (
  "id" int(11) NOT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE `testtable`;
2018-07-06 15:44:52 [INFO]  localhost:3306 skeematest: diff complete

2018-07-06 15:44:52 [DEBUG] Exit code 1
$ skeema push --debug --allow-unsafe
2018-07-06 15:44:58 [INFO]  Pushing changes from /home/steven/skeema/localhost:3306/*.sql to localhost:3306 skeematest
2018-07-06 15:44:58 [DEBUG] /home/steven/skeema/localhost:3306/testtable.sql: filename does not match table name of "testtable"
-- instance: localhost:3306
USE `skeematest`;
CREATE TABLE """testtable""" (
  "id" int(11) NOT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE `testtable`;
2018-07-06 15:44:58 [INFO]  localhost:3306 skeematest: push complete

2018-07-06 15:44:58 [DEBUG] Exit code 0 (SUCCESS)
$ mysql << done
> show tables in skeematest;
> done
Tables_in_skeematest
"testtable"
$ mysql << done
> describe skeematest.\`"testtable"\`;
> done
Field   Type    Null    Key     Default Extra
id      int(11) NO      PRI     NULL

```

System information:

```
$ uname -a
Linux --hostname-- 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

I really like the idea of skeema but as it stands right now, it looks like we won't be able to use this.  I'll check the code on my end to see what might be going on, but I'm not proficient in go, so no promises.

**Comment by evanelias** [comment]
Sounds very strange! I wonder if you have an unusual setting like [ANSI_QUOTES](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes) enabled... I haven't tested against that since I've never actually encountered it in production. Can you please show me the output of the following?

In mysql:
* `select @@sql_mode;`
* `SHOW CREATE TABLE testtable;`

On your local host:
* `cat /home/steven/skeema/localhost:3306/.skeema`
* `cat /home/steven/skeema/localhost:3306/testtable.sql`

Thanks!

**Comment by mv-steven** [comment]
Here's the mysql stuff:

```
mysql> select @@sql_mode;
+---------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                        |
+---------------------------------------------------------------------------------------------------+
| REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |
+---------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
///// This is 'testtable' before 'skeema push'
mysql> show create table testtable;
+-----------+-----------------------------------------------------------------------------------------------------------------+
| Table     | Create Table                                                                                                    |
+-----------+-----------------------------------------------------------------------------------------------------------------+
| testtable | CREATE TABLE "testtable" (
  "id" int(11) NOT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-----------+-----------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
///// This is 'testtable' after 'skeema push'
mysql> show create table `"testtable"`;
+-------------+---------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                        |
+-------------+---------------------------------------------------------------------------------------------------------------------+
| "testtable" | CREATE TABLE """testtable""" (
  "id" int(11) NOT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------------+---------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
And here are the files:
```
$ cat ~/skeema/localhost\:3306/.skeema 
schema=skeematest

[production]
host=localhost
port=3306
user=root
$ cat ~/skeema/localhost\:3306/testtable.sql 
CREATE TABLE "testtable" (
  "id" int(11) NOT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

Thanks!

**Comment by evanelias** [comment]
Thanks @mv-steven ! That is a very unusual `sql_mode` setting, which appears to be the cause of the problem. Skeema expects identifiers to be wrapped in backticks, not double quotes, but having the sql_mode be set to `ANSI_QUOTES` apparently changes this. I've been using MySQL for 15 years and I've never actually seen someone enable `ANSI_QUOTES` :) Is that sql_mode what Ubuntu gives you by default?

If you use a more normal `sql_mode`, things should work fine. The [default in 5.7](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-setting) is normally
`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

If you change to that in your mysql settings, Skeema should work properly. You'd need to do `SET GLOBAL sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'` to affect the running copy of mysqld, and also change in `/etc/my.cnf` (or wherever your mysql-server config file is) to persist across restarts.

I can add support for having Skeema automatically change this on a per-session basis, but it might be a few weeks.

**Comment by mv-steven** [comment]
I removed ANSI_QUOTES and now it's behaving as anticipated.  Thanks!!

To answer your question, yes, the version of mysql pre-packaged for Ubuntu comes with ANSI_QUOTES turned on.  This has affected other people as well.

**Comment by evanelias** [comment]
> yes, the version of mysql pre-packaged for Ubuntu comes with ANSI_QUOTES turned on

Very good to know! Sounds like Ubuntu uses very odd default settings :( Thanks again for reporting this. I'll keep this issue open to track.

**Comment by evanelias** [comment]
That's a relief, thanks. I have heard of some linux distributions doing unusual things by default, so definitely not unheard of, but still good to know that wasn't the case here.

Regardless, I'll still put a fix in Skeema soon to prevent ANSI_QUOTES from breaking anything. The simplest solution seems to be just setting session-level sql_mode for all connections in Skeema's connection pool. That way, Skeema can also be sure that other desirable sql_mode settings like strict mode are always enabled in its own sessions, regardless of what the global setting is. (Changing sql_mode at the session level doesn't impact the global setting, nor does it impact any other sessions, so this is harmless.)
