### ISSUE TITLE
skeema pull: add option to skip detection of new schemas

### ISSUE THREAD

**Issue by evanelias** [skeema/skeema#38]
By default†, when run from an instance-level directory, `skeema pull` will automatically look for "new" schemas (ones that don't yet have a directory) and will create and populate directories for them. This may be undesirable, especially when pulling from a dev instance. A dev instance might have random miscellaneous schemas that should not be tracked, and these misc schemas might not follow a naming convention, making `ignore-schema` regex option difficult to use here.

Adding a new option to `skeema pull`, say `--skip-new-schemas`, would handle this case more gracefully. One intended use could be to add `skip-new-schemas` it to the `[development]` section of a `.skeema` option file, so that using `skeema pull development` does not create dirs for these schemas. 

† Currently, the "find new schemas" pull behavior actually depends on your directory layout. If you only have 1 relevant schema per instance and use a "flat" directory structure combining the instance and single schema (e.g. created via `skeema init --schema x`), then new schemas are not auto-detected. This behavior will be retained regardless of this new option, since in this case the "instance-level" directory is the same thing as the "schema-level" directory.

**Comment by FlaviuRadulescu** [comment]
What it is wrong as a default behavior that all the schema that you define at the init ( imagining that we can have multiple comma separated schema) would be the ones that you work against. If you want to add additional schema  you can do that running init on the additional schema.

I believe this way is more predictable as you always know that the schema that you have initialized are the ones that you work with.

Having a default behavior to import all the schema when you run `skeema pull` can lead to undesired behavior. And this is the same for `--ignore-skeema` ,because if you have a new schema which will not match the regex you will end up with a new schema in the skeema folder and maybe even in production.

My recommendation it to configure the schemas you want just at the `skeema init` (with coma delimited schemas) either by defining `--skeema` or `--ignore-skeema` , and everything you do afterwards ( `skeema pull `) to update just these schemas. If you want to add additional schema, you can run `skeema init` again with some additional schemas. In this way everything is super predictable and easy to understand.

What do you think?

**Comment by evanelias** [comment]
@FlaviuRadulescu can you please explain your use-case in more detail -- how many production schemas do you want to track, and how many do you want to ignore? If there are a lot of production schemas you want to ignore, why do they need to be ignored? I want to help you, but I can't unless I understand what your use-case actually is.

Skeema is designed around the most common layouts in real-world use. I've been using MySQL for 15 years, ranging from tiny startups to literally the largest MySQL deployment on the planet, and there are 4 use-case patterns I've seen. Ordered from most common to least common:

1. MySQL instance with just one relevant schema: `skeema init --schema foo` handles this case and makes a "flat" directory, which combines both the instance and the schema configuration. No sense in a dir structure like `instance/schema/*.sql` if there's only one schema anyway. In this case, `skeema pull` already won't look for new schemas or create dirs for them.

2. MySQL instance with multiple relevant schemas: standard `skeema init`, optionally with `--ignore-schema` if there are some that should be omitted. It's rare that many schemas should be omitted though. Remember, advice is to run `skeema init` against *production*, not development. If you have many *production* schemas that should not be tracked, this is highly unusual in my experience.

3. MySQL instance with multiple schemas, but they all have the exact same set of tables -- essentially a sharded setup where each shard is a different schema, but several shards can live in the same instance. This is rare but definitely happens at scale (Facebook and Wordpress are two examples). Skeema supports this but the setup with some manual configuration. You run `skeema init --schema foo` pointing it at just one of the identical schemas, and then manually edit the generated .skeema file to change `schema=foo` to `schema=*`. Much like in case 1, `skeema pull` already won't look for new schemas or create dirs for them in this setup.

4. MySQL instance with multiple schemas; some have the exact same set of tables (shards) and some do not (special snowflakes). Again Skeema handles this, with some initial manual configuration -- this is what comma-separated schema names do. If in one subdirectory's .skeema you have `schema=foo,bar,baz` it means these 3 schemas all have the same set of table definitions.

> What it is wrong as a default behavior that all the schema that you define at the init ( imagining that we can have multiple comma separated schema)

Comma-separated schema names already have a defined meaning in the system (see 4. above), and this would break that.

Having to explicitly declare which schemas you want -- in a new additional way -- is also awkward for configuration. The filesystem representation already does that. The proposed new option `--skip-new-schemas` would just give you a way to say "I'm pulling from development (or whatever), but I don't want to find new schemas". This should give you want you want here, without breaking backwards compatibility for other Skeema users.

> Having a default behavior to import all the schema when you run skeema pull can lead to undesired behavior.

Whether it is desired or not depends entirely on your use-case. That's why this new option would just give you more flexibility to use in your use-case.

I think the current default behavior is sane: `skeema pull` is a command to make the filesystem look like the specified environment. If the specified environment has new schemas that the filesystem doesn't have, it's reasonable to create dirs and files so that the filesystem now reflects the environment.
