### ISSUE TITLE
diff support for generated columns

### ISSUE THREAD

**Issue by jianhaiqing** [skeema/skeema#49]
* json function
```
CREATE TABLE `t_open_api` (
  `c_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
   `c_create_time` datetime NOT NULL DEFAULT '1980-01-01 01:00:00',
  `c_update_time` datetime NOT NULL DEFAULT '1980-01-01 01:00:00',
  `c_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `route_pattern` varchar(100) GENERATED ALWAYS AS (json_unquote(json_extract(`c_route`,'$.pattern'))) VIRTUAL,
  `route_method` varchar(10) GENERATED ALWAYS AS (json_unquote(json_extract(`c_route`,'$.httpMethod'))) VIRTUAL,
  `c_sys_var_config` json DEFAULT NULL,
  `c_error` json DEFAULT NULL,
  `c_protect_res_field` json DEFAULT NULL,
  PRIMARY KEY (`c_id`),
  KEY `idx_route_method_pattern` (`route_method`,`route_pattern`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='OpenApi主体，c_identifier不唯一'
```
* FULLTEXT KEY `ft_question_text` (`question_text`)
```
CREATE TABLE `t_question` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `question_text` longtext NOT NULL COMMENT '题目正文',
  `question_type` int(11) NOT NULL DEFAULT '1' COMMENT '题目类型，1单选、2多选、3判断、4填空、5解答',
  `question_diff` int(11) NOT NULL DEFAULT '1' COMMENT '题目难度，1简单、2一般、3困难',
  `question_source` varchar(512) NOT NULL DEFAULT '' COMMENT '题目来源',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  FULLTEXT KEY `ft_question_text` (`question_text`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4
```

**Comment by evanelias** [comment]
Thank you for the report, but Skeema legitimately doesn't support diff'ing tables using generated columns or fulltext indexes yet. Mentioned in the [README](https://github.com/skeema/skeema/blob/master/README.md#status):

```
A few uncommon MySQL features -- such as partitioning, fulltext indexes, spatial types,
virtual columns -- are not yet supported. Skeema is able to *create* or *drop* tables
using these features, but not *alter* them. The output of `skeema diff` and `skeema
push` clearly displays when this is the case. You may still make such alters directly/
manually (outside of Skeema), and then update the corresponding CREATE TABLE
files via `skeema pull`.
```

Keeping this open but tagging with `feature request` and `help wanted`. If anyone in the open source community is interested in contributing code for this, the changes would be in the [tengo](https://github.com/skeema/tengo/) package, primarily affecting these files:
* [column.go](https://github.com/skeema/tengo/blob/master/column.go) would need modifications to be able to represent virtual columns
* [index.go](https://github.com/skeema/tengo/blob/master/index.go) would need modifications to be able to represent fulltext indexes
* [instance.go](https://github.com/skeema/tengo/blob/master/instance.go) Instance.querySchemaTables() performs schema introspection by reading `information_schema` and populating Go structs accordingly, would need changes for both features
* Test coverage in the corresponding *_test.go files

**Comment by trevorr** [comment]
Should spatial types be added to this issue, or made a separate issue? Adding support looks like it would be more straightforward than these other features:

```
2019-08-30 12:26:36 [WARN]  Skipping table `location_tz`: unable to generate DDL due to use of unsupported features. Use --debug for more information.
2019-08-30 12:26:36 [DEBUG] --- Expected CREATE
2019-08-30 12:26:36 [DEBUG] +++ MySQL-actual SHOW CREATE
2019-08-30 12:26:36 [DEBUG] @@ -3 +3 @@
2019-08-30 12:26:36 [DEBUG] -  `pt` point NOT NULL,
2019-08-30 12:26:36 [DEBUG] +  `pt` point NOT NULL /*!80003 SRID 4326 */,
2019-08-30 12:26:36 [DEBUG] @@ -8 +8 @@
2019-08-30 12:26:36 [DEBUG] -  KEY `ix_location_tz_pt` (`pt`(32))
2019-08-30 12:26:36 [DEBUG] +  SPATIAL KEY `ix_location_tz_pt` (`pt`)
```

**Comment by evanelias** [comment]
Please create a separate issue -- thanks! I can add some notes on potential implementation complexity from there.

**Comment by trevorr** [comment]
@evanelias Done, thanks! #97

**Comment by evanelias** [comment]
I forgot to update this issue last month, but [Skeema v1.3.0](https://github.com/skeema/skeema/releases/tag/v1.3.0) added support for fulltext indexes. So I'm editing this issue title to just track generated columns.

**Comment by evanelias** [comment]
I'm happy to say that generated column support has been implemented in master, and will be included in the next binary release.

**Comment by evanelias** [comment]
Today's release of [Skeema v1.4.0](https://github.com/skeema/skeema/releases/tag/v1.4.0) includes this functionality.
