### ISSUE TITLE
`skeema pull` pulls ignorable changes

### ISSUE THREAD

**Issue by mugli** [skeema/skeema#56]
This is probably an intended behaviour, but I'm creating the issue anyway just to be sure.

Incidentally, the `production` db has a table that looks like:
[1]
```
CREATE TABLE `my_table` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `SHOP_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_ID` (`USER_ID`),
  UNIQUE KEY `SHOP_ID` (`SHOP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

But in other environments such as `develop`, the table is defined as:
[2]
```
CREATE TABLE `my_table` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `SHOP_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SHOP_ID` (`SHOP_ID`),
  UNIQUE KEY `USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

The only difference is the order of how those unique keys are defined there. 

Now `skeema diff` or `skeema push` are smart enough to not care about this. But `skeema pull` is not. Every time I sync my local changes with `skeema pull -p develop`, the file gets updated anyway with the version from [2]. The next time someone else pulls from production, it gets changed again with version [1]. This makes reviewing changes a little noisy and annoying.

Is there anyway to fix this?

**Comment by evanelias** [comment]
Good question! Happily there are a couple ways to deal with this.

You could prevent it on the "pull" side, using the [normalize](https://github.com/skeema/skeema/blob/master/doc/options.md#normalize) option. This defaults to true, meaning `skeema pull` reformats files even if just making trivial cosmetic changes. You can disable it ad hoc using `skeema pull --skip-normalize`, or configure in a top level .skeema file, perhaps just for the develop environment, e.g.
```
[develop]
host=...
skip-normalize   # or equivalently, normalize=0
```

If you ever intentionally want to normalize the format, you can use `skeema lint` instead as needed.

Another solution would be to do a one-time push to all dev environments, making them use the same index order as prod. `skeema diff` and `skeema push` have an [exact-match](https://github.com/skeema/skeema/blob/master/doc/options.md#exact-match) option which tells it to even make changes that are purely cosmetic, such as adjusting index order. That would look something like:

```
$ skeema pull production
$ skeema diff --exact-match develop  # just to review the changes before pushing
$ skeema push --exact-match develop
```
If you have multiple dev databases though, you'd have to repeat that for each one.

Also one word of caution, I've noticed MySQL 8.0 has some unusual new changes regarding index ordering. From my testing, it seems that `SHOW CREATE TABLE` (which Skeema uses in a few ways) doesn't necessarily maintain the original order from `CREATE TABLE`, meaning that the push-based fix above may not solve the problem in MySQL 8.0.

**Comment by mugli** [comment]
Awesome! Thank you  👍 
Closing this issue now.
