### ISSUE TITLE
Support explicit renames of columns or tables

### ISSUE THREAD

**Issue by evanelias** [skeema/skeema#6]
See https://www.skeema.io/docs/requirements/#renaming-columns-or-tables, as well as discussion on issue #5, for background explanation on the complexity with supporting renames in a declarative system. These docs also mention the currently-supported work-arounds in Skeema.

This issue tracks the broader feature request of adding better support for renames. A couple potential ideas:

* Skeema's existing information_schema introspection is smart enough to know if only a name changed and no other attributes. The `diff` and `push` commands could get a new option which says to actually treat this situation as a rename when detected. The downside is that any other changes to the same table or col make the situation more ambiguous, implying that multiple options may be required to control the level of aggressiveness of the rename detector. This becomes especially relevant when, for example, updating a dev database that has missed several months of intermediate schema changes.

* Skeema could have new commands that handle execution of renames, along with automatic use of table comments and column comments to track the history of an object's original name. This is a more manual approach, but could permit very fine-grained control.

**Comment by shlomi-noach** [comment]
Heuristic detection of `rename`s is possible, based on column order (e.g. if column No. 4 out of 7 columns suddenly has a new name, it's _likely_ a `rename`).
I've grown to to be wary of such heuristics. 100% agree that combined with other changes this becomes exceedingly difficult to detect.

**Comment by adamdunkley** [comment]
Somewhat breaks the declarative nature of the schema, but is it worth considering using hinting in comments?

```SQL
CREATE TABLE _widgets (
  id int unsigned NOT NULL AUTO_INCREMENT,
  new_name varchar(30), -- rename from: name
  PRIMARY KEY (id),
  UNIQUE KEY name_idx (name)
) ENGINE=InnoDB;
```

I agree that heuristic approaches leave much to be desired, some description of the state change might be necessary.

**Comment by evanelias** [comment]
Yes, see 2nd bullet of the original issue text above :) The developer ergonomics with comments aren't great though.

Overall this issue is pretty low priority, as the effort-to-reward ratio isn't too compelling. Renames are very problematic for web applications requiring constant uptime. For this reason, many companies either forbid use of renames in production, or have a special process for them.

The main operational issue is that renames involve substantial application deploy-order complexities, since there's no way to rename a table/col at the exact same instant as new application code goes live. Unless your application somehow knows how to try both the old and new names (which most frameworks/ORMs cannot do), you'll either need to schedule a planned maintenance/downtime window, or accept some number of failed queries / user-facing errors.

**Comment by adamdunkley** [comment]
@evanelias Ah, sorry I misunderstood that second bullet 👍 

Appreciate its low priority, we don't have a particular need either as they are few and far between, as you say, and can be handled manually.

**Comment by evanelias** [comment]
Closing this issue from 7 years ago. Built-in rename support won't be added to Skeema in its current form. For some workarounds -- including pairing Skeema with a migration tool, or wrapping renames in a scheduled event -- see [this blog post](https://www.skeema.io/blog/2024/07/23/data-migrations-imperatives/).

Separately, *index* renaming is [now supported](https://www.skeema.io/blog/2024/07/01/v1120-released/#index-renaming) and works automatically, because that situation can be detected unambiguously.
