### ISSUE TITLE
Support for events

### ISSUE THREAD

**Issue by evanelias** [skeema/skeema#61]
Skeema does not yet support events. This issue tracks the feature request, which has been split out from #41.

Considering this low-priority, unless there's sufficient user interest.

**Comment by benmccann** [comment]
I wasn't sure what events were, so adding a comment here to clarify for others. They're basically MySQL cronjobs: https://dev.mysql.com/doc/refman/8.0/en/events-overview.html

**Comment by evanelias** [comment]
[Skeema v1.12](https://www.skeema.io/blog/2024/07/01/v1120-released/) is now available, with support for [events](https://www.skeema.io/docs/features/events/) as a [Premium Edition](https://www.skeema.io/download/) feature.
