### ISSUE TITLE
Support for triggers

### ISSUE THREAD

**Issue by evanelias** [skeema/skeema#62]
Skeema does not yet support triggers. This issue tracks the feature request, which has been split out from #41.

*July 2021 update: triggers are fully supported in the new [Premium edition](https://www.skeema.io/download/) of the Skeema CLI!*

**Comment by scoobs76** [comment]
Would love to see this support

**Comment by evanelias** [comment]
Thanks. This will either require a third-party pull request, or a corporation willing to sponsor the development time. Please let me know if interested in either option.

**Comment by scoobs76** [comment]
Hi Evan, curious as to your time/effort estimate for dev work on adding trigger support.  Thanks.

**Comment by evanelias** [comment]
I'd put a rough estimate at 5 to 10 days of dev work for triggers. 

One point of complexity is that MySQL 5.7+ and MariaDB 10.2+ added support for having multiple triggers per table with the same event and action time. Skeema could fully support this in theory, but it makes the diff logic harder, since it requires generating a FOLLOWS/PRECEDES clause or creating triggers in a specific order. So the estimate will depend on whether that's fully supported yet or not.

If interested in sponsoring the effort, I'm happy to discuss via email - please see https://www.indexhint.com/ for email address. Thanks!

**Comment by evanelias** [comment]
I'm happy to announce that the Premium edition of the Skeema CLI is now available! It has full support for triggers in all supported databases, including the multi-event/action functionality of MySQL 5.7+ and MariaDB 10.2+.

With the Premium CLI, `skeema init` and `skeema pull` will place `CREATE TRIGGER` statements in the same .sql file as the corresponding table. Users can easily add, remove, edit, or re-order trigger definitions, and `skeema diff` / `skeema push` will emit the corresponding DDL.

To learn more about the Premium edition CLI, check out the [feature comparison chart](https://www.skeema.io/download/) and [launch blog post](https://www.skeema.io/blog/2021/07/01/premium-cli/).
