### ISSUE TITLE
Support for views

### ISSUE THREAD

**Issue by evanelias** [skeema/skeema#63]
Skeema does not yet support views. This issue tracks the feature request, which has been split out from #41.

Views will require some care in `skeema pull`. MySQL does not store views in their "original" form; instead, `SHOW CREATE VIEW` returns them in their canonical form. There are pros and cons to having `skeema pull` normalize views, implying the best approach is a new boolean option controlling this behavior.

**Comment by Sparticuz** [comment]
Can you go over some of your thoughts for views, and the pros/cons?

**Comment by evanelias** [comment]
@Sparticuz do you mean thoughts/pros/cons of supporting views in Skeema? Or do you mean regarding use of views in MySQL/MariaDB in general?

**Comment by Sparticuz** [comment]
@evanelias Hah, in Skeema. Without support for views, I just decided to store the SELECT statement as a sql file. Skeema seems fine ignoring directories without .skeema in it, but ultimately views would be a very nice and important addition to Skeema. I'm sure if it was an easy addition, it would have been done by someone by now.

**Comment by evanelias** [comment]
It's maybe a week or two of work. So far no one has offered to sponsor that work or submit a pull request. Otherwise it'll end up in the eventual commercial version of Skeema.

**Comment by arditti** [comment]
Don't know how i missed this issue - was debugging for hours till i realised there might be lack of support in Views.

Supporting Views will much improve how we work with skeema!

**Comment by evanelias** [comment]
Sorry to hear about the lengthy debugging session! The best reference for this sort of thing is the [requirements documentation](https://www.skeema.io/docs/requirements/), especially the [unsupported features](https://www.skeema.io/docs/requirements/#unsupported-features) section.

**Comment by evanelias** [comment]
I'm happy to announce that full support for views has been implemented in the upcoming premium edition of the Skeema CLI. Launch is just a few weeks away! Sign up to be [notified on launch day](https://www.skeema.io/premiumcli/?ref=views).

Also, for any heavy users of views: if you're up for trying a preview release, so far I still have room for a couple more companies in the beta test group. Although the views logic has been tested pretty extensively already, more testing never hurts :) If your company is interested, please mention it in the Comments field of that same [form](https://www.skeema.io/premiumcli/?ref=views).

**Comment by evanelias** [comment]
Finally closing out this issue -- I'm happy to announce that the Premium edition of the Skeema CLI, including full support for views, is now available! Learn more at the [feature comparison chart](https://www.skeema.io/download/) and [launch blog post](https://www.skeema.io/blog/2021/07/01/premium-cli/).
