### ISSUE TITLE
`skeema help` should show that `skeema init help` is a possible combination

### ISSUE THREAD

**Issue by d33psky** [skeema/skeema#66]
`skeema help` output
```
Usage:
      skeema [<options>] <command>

Commands:
      add-environment  Add a new named environment to an existing host directory
      diff             Compare a DB instance's schemas and tables to the filesystem
      help             Display usage information
      init             Save a DB instance's schemas and tables to the filesystem
      lint             Verify table files and reformat them in a standardized way
      pull             Update the filesystem representation of schemas and tables
      push             Alter tables on DBs to reflect the filesystem representation
      version          Display program version
```
excludes `skeema init help` while it is supported.
Explaining that the help option can be combined with the other commands should help newcomers.

**Comment by evanelias** [comment]
First, pretty much every Linux command suite I've ever used works in this fashion, so this should not be surprising or unexpected.

Second, the output also includes this line, which you cut off in your issue:

```
  -?, --help[=value]                  Display usage information for the specified command
```

For example, all of these combinations work properly and are completely equivalent: `skeema help diff`, `skeema diff --help`, `skeema diff help`, `skeema --help=diff`

While I agree the help information could be improved (nothing's ever perfect!), this issue report feels trivial and unnecessary. Please understand Skeema is primarily a single-person bootstrapped project, and I simply do not have the bandwidth for trivial / nitpick issues unless a corresponding pull request is submitted with them.
