### ISSUE TITLE
Gibberish showed up in the field comment.

### ISSUE THREAD

**Issue by ConnorWeng** [skeema/skeema#7]
Gibberish showed up in the field comment. The comment was written in Chinese. Is there any workaround?

**Comment by evanelias** [comment]
Hi @ConnorWeng, I'm happy to help debug this if you can provide an example of how to repro the issue. Perhaps Skeema is connecting using the wrong charset by default? 

Please try supplying `--connect-options='charset=utf8mb4'` on Skeema's command-line and let me know if that fixes the problem? If so, I will change this to be the default.

**Comment by ConnorWeng** [comment]
I figured out that the problem is caused by our developers using wrong encoding in their sql files. The default utf8 is fine. Thanks a lot.
