### ISSUE TITLE
`skeema add-environment` doesn't allow --schema option

### ISSUE THREAD

**Issue by RJPercival** [skeema/skeema#75]
It appears that configuring different environments to use different schema names is a supported use case (e.g. see https://github.com/skeema/skeema/issues/47#issuecomment-439772649). However, the `skeema add-environment` command prints "Option schema cannot be set via command line for this command", so hand-editing of the .skeema file is required. This makes it difficult to automate this scenario. Could this flag be implemented for this command please?

**Comment by evanelias** [comment]
Thank you for the feature request. Indeed, `skeema add-environment` is currently quite limited. Ideally it should handle more situations, but there's actually a fair bit of complexity in handling all possible topologies:

* Each environment is a different mysqld instance, with multiple schemas per instance
* Each environment is a different mysqld instance, with a single schema per instance (and a flattened dir structure, e.g. created using `skeema init --schema ...`)
* Multiple environments sharing a single mysqld instance; each environment is a different schema on the same instance
* Some arbitrary mix of the above (e.g. perhaps there are some schemas that only exist in some environments, and are colocated when they do exist)
* Sharded topologies, at either the mysqld or individual schema level

Although Skeema's configuration system can handle all of these, `skeema add-environment` only works in the first case currently. For the other cases, if you need to add new environments in an automated fashion, I would recommend manipulating .skeema files using a custom script that matches your desired topology.

An improved `skeema add-environment` would need to handle various permutations to auto-detect which topology is in use. E.g. `host` specified in same .skeema file as `schema` or not; host supplied on CLI matches one that already has a different environment or not; etc...

I'll keep this open as a feature request, but I don't think I'll be able to pick this up soon myself unless a company wants to sponsor the development time. I'll add the `help wanted` label in case a third-party contributor wants to give it a try. For now I've adjusted the command's help text in e5fa8b5.

**Comment by evanelias** [comment]
Closing due to lack of third-party interest
