### ISSUE TITLE
Any support for development_ vs production_ prefix?

### ISSUE THREAD

**Issue by newhook** [skeema/skeema#76]
Great looking project. We're excited to try it out! However, I immediately ran into an issue. In development we use a database prefix development_<name>, and in production we have production_<name>. Is there any support in the tool for this?

**Comment by evanelias** [comment]
Thanks for trying out Skeema!

You can use different schema (database) names in prod vs dev -- Skeema supports any arbitrary layout / topology. You just need to edit the .skeema files manually one time to achieve the desired layout. For example,

```ini
# config at the top of the file sets defaults for all environments, but can be
# overridden (on a per-key/value basis) by each environment if desired
ignore-table=_new$

# config for production environment, i.e. used for `skeema push production` (as
# well as just `skeema push`, since "production" is used if no environment is
# specified on CLI)
[production]
schema=production_mydb

# config for development environment, i.e. `skeema push development`
[development]
schema=development_mydb
```

Your repo layout will depend a bit on whether each environment has 1 schema vs several, and whether environments are colocated on a single mysql server vs different servers. This will determine whether you want to define `host` in the same .skeema file as `schema`, vs having multiple layers of subdirs. If you describe your db topology more, I'm happy to give guidance.

If you have many schemas per environment, and they all follow a naming convention, you can even do fancy programmatic things with shell-outs, such as
```ini
schema=`echo {ENVIRONMENT}_mydb`
```
for example, that will yield `staging_mydb` when running `skeema diff staging`. That's overkill for most users though :) Anyway, more details in the [option doc](https://github.com/skeema/skeema/blob/master/doc/options.md#schema).

**Comment by evanelias** [comment]
Closing this out, but please feel free to re-open if you have any follow-up questions.
