### ISSUE TITLE
Exitcode 1 on "successful" diff

### ISSUE THREAD

**Issue by Gerben-T** [skeema/skeema#90]
I'm pretty dependent on the exit codes for Skeema, because my build server automatically fails whenever it receives a non-zero exit code.

When i run `skeema diff --debug=true` i get the following output

```
2019-08-01 09:11:58 [INFO]  Generating diff of xxxxx:xxxx xxxxx vs /xxxx/*.sql
-- instance: xxxxx:xxxxx
USE `xxxxx`;
ALTER TABLE `xxxxxx` AUTO_INCREMENT = 9834579;
2019-08-01 09:11:58 [INFO]  xxxxx:xxxx xxxxx: diff complete
2019-08-01 09:11:58 [DEBUG] Exit code 1
```

Why is Skeema returning an exit code of `1` when it is successful?

**Comment by Gerben-T** [comment]
I just ran the `skeema diff --help` and saw there the explanation for the exit codes

```
An exit code of 0 will be returned if no differences were found, 1 if some
differences were found, or 2+ if an error occurred.
```

Could you add this to the docs, because i didn't have an interactive shell on my server while testing my build steps and thus running this never crossed my mind..

**Comment by evanelias** [comment]
Sorry for the confusion! I plan on revising the web docs in a few weeks to include pages on each command.

fwiw, `skeema diff`'s exit codes are intentionally similar to the standard textual GNU `diff`, which also returns 1 if differences exist vs 2+ for error. Most of Skeema's commands are designed to be used in pipelines and use exit code 1 to mean something non-fatal; for example `skeema lint` will return 1 if linter warnings are found, but no linter errors or fatal exceptions.
