### ISSUE TITLE
Add option like --workspace to use separate mysqld instance

### ISSUE THREAD

**Issue by paulcaskey** [skeema/skeema#94]
In addition to **--workspace=<other-db-name|docker>**, an option would be very useful to offload all workspace operations to a different Mysql server. This could be on localhost or other. A full DSN like **user:pass@host:port/schema** would be perfect. This could be a new option rather than overloading the existing "workspace" option.

**Comment by evanelias** [comment]
Thank you for the feature request. I agree this could be useful for anyone who prefers using a non-Dockerized mysqld for handling workspace operations.

A few implementation notes:
* The [workspace](https://github.com/skeema/skeema/blob/master/doc/options.md#workspace) option is an enum (it can currently be set to either "temp-schema" or "docker", you can't set it to a schema name). In implementing this feature, it would get a new third possible enum value (TBD / open to suggestions. "external"? "offload"?).
* One or more additional new options would be added to control connection information for the workspace mysqld, but I'm not really convinced a DSN is the right way to go:
  * Static DSNs are less dynamic than other Skeema configuration methods, many of which permit optional shellouts for maximum flexibility. No preexisting options in Skeema use DSNs.
  * Users may or may not want to reuse the same user/pass auth info as in prod hosts. We'd need more community feedback to determine this. If supporting different auth info than prod, care must be taken to avoid requiring storing a password in a .skeema file, as passwords are usually undesirable to keep in version control.
  * The schema name portion should just re-use the existing [temp-schema](https://github.com/skeema/skeema/blob/master/doc/options.md#temp-schema) option value.

**Comment by evanelias** [comment]
Skeema v1.9.0 has been [released](https://www.skeema.io/blog/2022/11/30/v190-released/), and the Premium edition now includes this feature via the [temp-schema-environment](https://www.skeema.io/docs/options/#temp-schema-environment) option.

This allows you to fully configure the workspace host, by defining it in different environment section in your .skeema files, overriding whichever connectivity options you need (host, user, password, SSL options, etc). Or you can re-use some other existing environment, to achieve things like "run production workspaces on the staging db".
