### ISSUE TITLE
Password management

### ISSUE THREAD

**Issue by kaihendry** [skeema/skeema#99]
I put the password in schemas/.skeema to avoid prompts, but now git wants to check it in. Is there some better place to store sensitive passwords for {dev,demo,prod} environments?

With thanks!

**Comment by evanelias** [comment]
Skeema supports the following "global" option file paths, where you can store things outside of the repo:

* /etc/skeema
* /usr/local/etc/skeema
* ~/.my.cnf (special parsing rules apply)
* ~/.skeema

Please see https://github.com/skeema/skeema/blob/master/doc/config.md#specifying-options-via-option-files
